### ISSUE TITLE
Container message overflow

### ISSUE THREAD

**Issue by SteamDosh** [SkyrimTogether/issues-game#10]
## Description

Server can crash depending if container message is too high (approx 650-700+)

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim
    * The Elder Scrolls V: Skyrim Special Edition

## Reproduction rate

1 hundo

**Comment by WopsS** [comment]
Haven't we set a rate limiter?

**Comment by SteamDosh** [comment]
Rate limit doesn't look at the size of the message, so if the fullContainer send has 600-700+ entries the server has an issue unpacking it and crashes

**Comment by SteamDosh** [comment]
Limit of 12 messages per packet has been placed, still doesn't resolve the conflict of 500+ entries per packet

**Comment by SteamDosh** [comment]
Will close for now until this becomes an issue
