### ISSUE TITLE
Can not properly connect to server

### ISSUE THREAD

**Issue by usbalbin** [SkyrimTogether/issues-game#102]
First of, thank you for this awesome project!

## Description

Can not connect to server. When either party leader or myself press "Launch Party" the ingame log says I'm connected but I can not see anyone. I can send and recieve chat messages. The "Skyrim Together Debug Console" keeps spamming `event=game_unload_resources`.

My game seems to think that I am connected so I do actually have the option to disconnect.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Accept party invite
3. Party leader launches party
4. My game reports that it is connected and server version etc. My friends does not see me as connected. Console keeps spamming about 5 `event=game_unload_resources` / second.

## Reproduction rate

Every time.

## Expected result

I would expect to get connected and thus be able to see the other party members when they are in the same area. 

## What I have tested

* Restarted Steam
* Reinstalled game
* Reinstalled harbor
* Tested different game saves
* Rebooted computer
* Disabled firewall

## Your environment

I have tested on two systems. System B works as expected.

System A:
* The described issue
* The Elder Scrolls V: Skyrim Special Edition
* Windows 10 latest updates

System B:
* Everything works fine
* The Elder Scrolls V: Skyrim Special Edition
* Windows 10 have not installed windows updates since one of the large ones.

## Evidence
```
2019-01-26 02:39:26,188 WARNING [default] event=load_skse error=skse_not_found_or_different_version expected_version=v0.2.0.12
[0x7FF7F33454C0] ANOMALY: meaningless REX prefix used
[0x7FF7F378A240] ANOMALY: meaningless REX prefix used
2019-01-26 02:39:26,622 INFO [default] event=overlay_load_start type=1
[0x7FF7F37EB660] ANOMALY: meaningless REX prefix used
2019-01-26 02:39:26,976 INFO [default] event=overlay_load_done code=0
[0x7FF7F37931E0] ANOMALY: meaningless REX prefix used
[0x7FF7F378F750] ANOMALY: meaningless REX prefix used
2019-01-26 02:39:31,718 INFO [default] event=create_resources hwnd=0000000000120760

.........

2019-01-26 02:40:40,895 INFO [default] event=game_unload_resources
2019-01-26 02:40:40,913 INFO [default] event=game_unload_resources
2019-01-26 02:40:40,931 INFO [default] event=game_unload_resources
2019-01-26 02:40:40,949 INFO [default] event=game_unload_resources
2019-01-26 02:40:40,967 INFO [default] event=game_unload_resources
2019-01-26 02:40:40,985 INFO [default] event=game_unload_resources
2019-01-26 02:40:41,003 INFO [default] event=game_unload_resources
2019-01-26 02:40:41,021 INFO [default] event=game_unload_resources
2019-01-26 02:40:41,039 INFO [default] event=game_unload_resources
2019-01-26 02:40:41,057 INFO [default] event=game_unload_resources
2019-01-26 02:40:41,075 INFO [default] event=game_unload_resources

```

Please let me know if I should include something else.

**Comment by Dumbeldor** [comment]
Hi @usbalbin.
Thank you for taking the time to write such a complete issue.
Did you see your friend in the group ui?

**Comment by usbalbin** [comment]
@Dumbeldor I can see friends and they me up until step 3.

@Ueine all games are in English without subtitles.

**Comment by usbalbin** [comment]
I can also add that after step 3 the ui reports ~64packets/s up and down. My friends game reports about the same speed.

**Comment by usbalbin** [comment]
I was invited to a friends party, same issue as usual. Then i alt tabbed out of the game and started writing the above comment. The log stops spamming as soon as I tab out of the game. Later my friend also invited me to watch his steam broadcast of trying to play skyrim with a Guitar Hero guitar. Atleast 5 minutes later I hear the drum sound and I am connected!

I will do some more testing and report back.

**Comment by usbalbin** [comment]
We could see each other moving, however attacking my friend had no effect on him and vise versa. After a couple of minutes the log started spitting out warnings and finally the ui said `Connection failed due to an error.`.

[My log](https://gist.github.com/usbalbin/d61eda31b5c775eda9a5dc6f19e54b0d)
[Friends log](https://gist.github.com/Wratox/8d75a41a081920eea7cb4f517964e202)

After getting the above error we tried connecting again and got the same error immediately after the "Tick rates:" line in the chat.

After restarting Skyrim and harbor, we are still getting `Connection failed due to an error.`

**Comment by usbalbin** [comment]
Forgot to mention that I installed the harbor update just before the events described here

> I was invited to a friends party, same issue as usual. Then i alt tabbed out of the game and started writing the above comment. The log stops spamming as soon as I tab out of the game. Later my friend also invited me to watch his steam broadcast of trying to play skyrim with a Guitar Hero guitar. Atleast 5 minutes later I hear the drum sound and I am connected!
> 
> I will do some more testing and report back.

**Comment by usbalbin** [comment]
After my friend also updated Harbor the `Connection failed due to an error.` no longer appears. And I can now join him, however as with #117 as soon as he uses magic (I have not tested to use magic myself) my game crashes yet we still can not see each other.

Thus the problem in the first post seems to have been fixed by the Harbor update.

**Comment by Pokang** [comment]
Thank you very much for detailing your issue, it really helped us a lot.
The magic making the game crash has been fixed in today's patches.
Closing the issue accordingly.

**Comment by usbalbin** [comment]
The problem has reappeared and has occurred in 3/3 attempts today.

**Comment by usbalbin** [comment]
Last time tested was 7th of February and this has not been an issue since the harbor update mentioned above.

**Comment by usbalbin** [comment]
We have tried with completely new saves, both me and friend.
