### ISSUE TITLE
Stuck on Inventory Screen

### ISSUE THREAD

**Issue by ShowMeTheNugget** [SkyrimTogether/issues-game#103]
## Description

While switching armor my game got stuck in the Inventory and I couldn't close it (tried: Scrolling mouse wheel, using arrow keys, pressing Esc, pressing I, nothing worked, even Alt+F4. Had to alt+tab and quit game.) I was in Alvor's house, talking to Hadvar for the first time after exiting the tutorial. I was the cell host. It was NOT FROZEN, because I could equip/unequip what I had highlighted, but I couldn't select anything else.

Related formIDs|

None/Unknown

## Steps to reproduce

1. Go to Riverwood for first time after tutoriali
2. Enter Alvor's house
3. Talk to Hadvar
4. Open Inventory and equip another armor
5. Stuck.

## Reproduction rate

Not sure

## Expected result

Be able to use inventory normally without becoming stuck and having to force close the game.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

None

**Comment by Pokang** [comment]
This should not be an issue anymore, since we removed the no pause code, that makes it in line with other menus. Please reopen if it occurs other issues with sync or the mod in general.
