### ISSUE TITLE
Merchant window issue

### ISSUE THREAD

**Issue by SlaiGaming** [SkyrimTogether/issues-game#104]
## Description

When shopping at a merchant, the shop window is unable to be controlled with mouse or keyboard until pressing tab. Left clicking or pressing E activates a dialogue option with the merchant.

## Steps to reproduce

How to reproduce this issue:

1. Talk to any merchant.
2. Say "What do you have for sale?"
3. The shop UI will be unusable until pressing tab.

## Reproduction rate

Every time.

## Expected result

The shop window should be usable and the dialogue options should be unusable while in the shop window.

## Your environment

The Elder Scrolls V: Skyrim Special Edition

**Comment by Thesa22** [comment]
This is the same as issue #53 https://github.com/SkyrimTogether/issues-game/issues/53
