### ISSUE TITLE
Issue with Dragons Reach

### ISSUE THREAD

**Issue by WoahitsBeau** [SkyrimTogether/issues-game#105]
## Description

Entering dragons reach as host or client crashes the game

Related formIDs|
---------------|
[Flames - 12FCD](http://en.uesp.net/wiki/Skyrim:Flames)|
[Nazeem - 1A6A4](http://en.uesp.net/wiki/Skyrim:Nazeem)|

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Enter Dragons reach

## Reproduction rate

All 5 times I've tried.

## Expected result

Not crashing the game

## Your environment

    The Elder Scrolls V: Skyrim
    The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

Show us what happen.

**Comment by SteamDosh** [comment]
This is impossible to debug without a dump crash.
