### ISSUE TITLE
General Crashing, Issue with game location?

### ISSUE THREAD

**Issue by LNVengeance** [SkyrimTogether/issues-game#106]
## Description

General crashing, might be related to hardware and location of my skryim game? (Skyrim game is not in Local disk C: it's in another drive directly hooked up internally)

Related formIDs|

N/A

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Crash after a awhile 1-10 minutes.

## Reproduction rate

Every time, intervals differ.

## Expected result

N/A

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

Just crashes.

**Comment by SteamDosh** [comment]
Impossible to debug without a dump crash file.
