### ISSUE TITLE
Summons cause other players to crash

### ISSUE THREAD

**Issue by Aerzzy** [SkyrimTogether/issues-game#107]
## Description

Whenever a player summons a familiar any other summon other players around them immediately CTD.

Related formIDs|
---------------|
[Conjure Familiar- 000640b6](https://en.uesp.net/wiki/Skyrim:Conjure_Familiar)|

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Summon anything
4. Someone else crashes

## Reproduction rate

Tested multiple times with Conjure Familiar spell.

## Expected result

A familiar is summoned and nobody crashes.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

**Comment by Pokang** [comment]
Can you confirm me this is still the case on our latest patch please?

**Comment by anathemamask** [comment]
I experienced this after the latest patch release - but only after the summon entered combat.

**Comment by f13rce** [comment]
Thank you for also providing a formID. Will have a look.

**Comment by f13rce** [comment]
Cannot reproduce this - seems to work fine.
![489830_20190129181446_1](https://user-images.githubusercontent.com/39367107/51926538-cb839700-23f1-11e9-8e9c-924bb28adde7.png)

Please reopen if you find anything more specific that causes this.
