### ISSUE TITLE
Controlls disable on guard assault

### ISSUE THREAD

**Issue by mihalisp** [SkyrimTogether/issues-game#111]
## Description

Game controls dont respond when a guard wants me to follow him in prison.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Assault a guard.

## Reproduction rate

Didn't check

## Expected result

Game controls won't respond

## Your environment

* The Elder Scrolls V: Skyrim Special Edition

**Comment by Pokang** [comment]
Can't seem to reproduce, please reopen with further info if you're still experiencing the issue.
