### ISSUE TITLE
Chat message length is limited on server, but not client

### ISSUE THREAD

**Issue by Tactitocalon** [SkyrimTogether/issues-game#112]
## Description

The chat UI seems to have a length limit (of 127 characters, seemingly) on chat messages on the server-side, but not the client-side.

The client allows you to send chat messages of any length, but any message above 127 characters is dropped and does not show up in the chat UI for any player in the party.

Could the client have a limit on the input field for chat?

(It would also be nice if the limit was increased from 127 characters to something a lot higher, for roleplaying purposes.)

Related formIDs|
---------------|

## Steps to reproduce

How to reproduce this issue:

Input any chat message above 127 characters length. It does not appear to be sent.

## Reproduction rate

100% reproduction rate

## Expected result

Limit input on the client to the maximum set by the server.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

Show us what happen.

**Comment by Pokang** [comment]
That is very interesting, thank you for your report, we'll definitely be investigating this.

**Comment by Dumbeldor** [comment]
Hi @Tactitocalon 

Thanks for your suggestion, I just developed this. I close the issue.
