### ISSUE TITLE
Launcher download is not working

### ISSUE THREAD

**Issue by Raki72** [SkyrimTogether/issues-game#116]
Trying to access the launcher file from here: 
https://s3.eu-central-1.amazonaws.com/skyrim-together-harbor/Harbor-1.0.0-alpha.7.exe

I receive an error message:

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>AA09E1ED2A62B24C</RequestId>
<HostId>
Xg3IEs/uyXMvF1GHA6Xq2W9rjm5hQ+hJpJO/YQXxfYm6rpQId/Ur4kuVkBqmJGqnvSMAe7L2KLg=
</HostId>
</Error>`

Do I need an active AWS account for the download? Is the URL correct?

**Comment by Ueine** [comment]
thats the oldest link, its not active anymore, go on reddit and pick the new link.

**Comment by Raki72** [comment]
Confirmed. Latest download link can be found on reddit here: 
https://www.reddit.com/r/SkyrimTogether/comments/ajnsmd/closed_beta_is_out_now/
