### ISSUE TITLE
Magic Crashes Other Player

### ISSUE THREAD

**Issue by SvalintheShield** [SkyrimTogether/issues-game#117]
## Description:
Two players, both using Windows 10. Whenever we tried casting the spells Flames, Sparks, or Conjure Familiar the game crashed for the person who was not casting, regardless of who was the group leader.

## Issue:
Casting magic spells immediately crashes the player that was not casting. 

## Step to Replicate:
-1. Start Game
-2 Connect with friend
-3 Cast magic spell
-4 Person who didn't cast spell crashes to desktop

## Reproduction Rate:
100% over 10 tries.

**Comment by f13rce** [comment]
Do you have a .dmp file for us that we can analyze? Should be located in SkyrimSE/Data/Online/. :)

**Comment by SvalintheShield** [comment]
[Online.zip](https://github.com/SkyrimTogether/issues-game/files/2799379/Online.zip)

**Comment by SvalintheShield** [comment]
There's 3-4 of them in there.

**Comment by RaivoKoot** [comment]
I have the exact same problem

**Comment by Pokang** [comment]
This has been fixed in our latest patch, closing the issue.
Thank you for reporting in!
