### ISSUE TITLE
Crash on Tasting Ingredients

### ISSUE THREAD

**Issue by jamesmp** [SkyrimTogether/issues-game#118]
## Description

Another player tasting a potion ingredient causes the player witnessing it to crash

## Steps to reproduce

How to reproduce this issue:

1. Both players enter a cell
2. One player eats a potion ingredient
3. Witnesses crash

## Reproduction rate

100%

## Expected result

That potion or magic effects play on the tasting character, or no visible effects, but not crashing.

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition

**Comment by jamesmp** [comment]
This may be related to general magic bugs early in the closed beta, will test again when I get the chance.

**Comment by Pokang** [comment]
Let me know if this is still an issue on our latest patch if you have the chance to try it out!

**Comment by jamesmp** [comment]
This doesn't seem to be an issue any longer, great work!
