### ISSUE TITLE
Can't open Skyrim from loader screen

### ISSUE THREAD

**Issue by TomTheMystik** [SkyrimTogether/issues-game#121]
## Description

Pressing "Play" from main Skyrim Together launcher screen results in an error message saying "loader is in the incorrect folder." with no further information. Also in the bottom left it says "Seeding" without end no matter how long you leave it with a pause button next to it that doesn't do anything when pressed if that's relevant.

## Steps to reproduce

How to reproduce this issue:

1. Open the launcher.
2. Log in.
3. Press "Play".
4. Error.

## Reproduction rate

Every time.

## Expected result

For Skyrim to open i guess.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim

## Evidence (optional)

Show us what happen.

![](https://puu.sh/CCNlx.png)

**Comment by Pokang** [comment]
That is a super common issue which is fixed by following what's written in this post: https://www.reddit.com/r/SkyrimTogether/comments/ajxkwr/all_known_fixes_for_issues_with_skyrim_together/
Closing the issue.
