### ISSUE TITLE
Crashing leaving Whiterun

### ISSUE THREAD

**Issue by gjsouth42** [SkyrimTogether/issues-game#126]
## Description

I played a bit yesterday with someone and had some issues with teleporting but today i load up and as i leave whiterun, i crash. I attempted it 3 more times and it crashed each time

Related formIDs|
---------------|
[Flames - 12FCD](http://en.uesp.net/wiki/Skyrim:Flames)|
[Nazeem - 1A6A4](http://en.uesp.net/wiki/Skyrim:Nazeem)|

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Activate front entrance of Whiterun(From inside)
4

. Crash.

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.

## Reproduction rate

How many times can you reproduce it?

## Expected result

Describe your expected result.

## Your environment

* Game edition (choose on which edition do you have problems):
  
[20190126-164835-18296-21752.zip](https://github.com/SkyrimTogether/issues-game/files/2799658/20190126-164835-18296-21752.zip)

    * The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

Show us what happen.

**Comment by Neusor** [comment]
Seems like you may have had an corrupted save that loaded in things that made your game crash every time you left Whiterun

**Comment by f13rce** [comment]
Likely to be fixed in an upcoming patch for savegame tweaks. Please reopen it if it keeps happening.
