### ISSUE TITLE
Location drop down menu not showing

### ISSUE THREAD

**Issue by Ueine11** [SkyrimTogether/issues-game#13]
## Description

The login screen on the location choice drop down menu screen thing doesn't show, it still clickable.

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition

    *Rockhouse Build 2/01/18 00:10

* Mods used:

None

## Reproduction rate

everytime

## Steps to reproduce

open the chat ui and click the login button and click on the locations window.

## Actual result

the menu exist, but is not shown.

## Expected result

screen with locations should appear.

**Comment by skreborn** [comment]
The location selector is a standard dropdown control. It is not supposed to open a new window. You should be able to click on the arrow on the right side - although I believe clicking inside should do it, too - to display your options, just like you would in a browser.

**Comment by Enieu** [comment]
[2018-01-02 14-19-59.zip](https://github.com/SkyrimTogether/issues-game/files/1598042/2018-01-02.14-19-59.zip)

**Comment by skreborn** [comment]
Well, that's new to me. Anybody else experienced this? The exact same version of Chrome is supposed to be running for everyone, and thus the control should work the same.

**Comment by Gamepaw** [comment]
This is also happens for me, on the latest version we've got. Can control it with the arrow keys also but just can't see the options or the drop down menu.

Also, some spellchecking to do :)

**Comment by Gaaraofthesand** [comment]
Wait how do you have skyrim online already? I thought it wasn't released.

**Comment by f13rce** [comment]
You're correct, the mod isn't released yet. All developer and some chosen helpers have access to the mod. This page is just for public bug/issue reporting. More info can be found here: https://www.reddit.com/r/SkyrimTogether/

**Comment by Dumbeldor** [comment]
This menu is removed from the UI. We now connect from the launcher.
So i close this issue.
