### ISSUE TITLE
Favorites menu causes game to act like it is paused.

### ISSUE THREAD

**Issue by F1r3w477** [SkyrimTogether/issues-game#131]
## Description

When opening the favorites menu, if you are looking at your friend, they will stop moving in the background as the menu comes into focus, once you leave the menu, if your friend was moving, they will teleport to where they were. Also, all sound stops as if the game is paused. You can get hit by enemies while this happens.  When hitting escape, you can still hear music and sfx, and see your friend moving in the background.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Open favorite menu

## Reproduction rate

Pick a number between 1 and 10000

## Expected result

Act as if it was an inventory window, or chat, or any other overlay that doesn't freeze the background.

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition

**Comment by f13rce** [comment]
This is indeed intentionally for now as we're trying to unpause the favorites menu. This does mean you can assign numbers to your weapons and use them as hotkeys. Will close for now as the pausing will be in one separate issue.
