### ISSUE TITLE
Occasional CTD Opening Containers/Menus

### ISSUE THREAD

**Issue by IceMaverick** [SkyrimTogether/issues-game#132]
## Description

While playing around with 1 friend for a few hours, we would occasionally - with no similar circumstances cropping up - experience a cell-client CTD when they would open their inventory or a container.

## Steps to reproduce

How to reproduce this issue:

Issue is sporadic and appears to strike at random rather than for any specific event. More testing needed to determine if it's reproducible

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.
GitHub doesn't support the attachment of .dmp files in bug reports. Here's a Drive link instead:
https://drive.google.com/file/d/1rqZTWWCyxTR9HGcDacxVBJrbY1pBBK4p/view?usp=sharing

## Reproduction rate

Occasional. Would happen approximately twice every hour or so of play.

## Expected result

For clients to not CTD upon opening an inventory menu.

## Your environment
* The Elder Scrolls V: Skyrim Special Edition
* SKSE SE 2.0.12
* No Other mods or plugins during this play-test.

**Comment by ProhorovIlja** [comment]
It might be happening because you're using SKSE and it has issues with a Skyrim Together Mod.
Try to play without SKSE and disable the mods, which require SKSE to be installed.

**Comment by IceMaverick** [comment]
> Try to play without SKSE and disable the mods, which require SKSE to be installed.

As quoted in the original report, no other mods or plugins were used during the time in which this report was generated. It was just Skyrim running SKSE with no other mods or plugins.

**Comment by Pokang** [comment]
This should not be an issue anymore, since we removed the no pause code, that makes it in line with other menus. Please reopen if it occurs other issues with sync or the mod in general.
