### ISSUE TITLE
My game freezes every 10 mins

### ISSUE THREAD

**Issue by SkyrimForNords** [SkyrimTogether/issues-game#133]
## Description

 My game freezes every 10 mins no matter who is hosting. Also I have win7 and I've already followed your advice to change compatibility, but it didnt help me.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Play 5-12 minutes.
4. Crash.

## Reproduction rate

100%

## Expected result

Not haveing this bug anymore

## Your environment

win7 x64

The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)
[20190127-154446-8864-8792.zip](https://github.com/SkyrimTogether/issues-game/files/2800069/20190127-154446-8864-8792.zip)

**Comment by mineas312** [comment]
Read that https://www.reddit.com/r/SkyrimTogether/comments/ajxkwr/all_known_fixes_for_issues_with_skyrim_together/
It is caused by windows 7

**Comment by f13rce** [comment]
>win7 x64

Please check out this possible fix: https://old.reddit.com/r/SkyrimTogether/comments/ajxkwr/all_known_fixes_for_issues_with_skyrim_together/

Please re-open the report if it persists, alongside dmp files and specific descriptions what you were doing at the time.
