### ISSUE TITLE
Animations Freeze, Teleport walking. (When EU-players connect with AU/US Players)

### ISSUE THREAD

**Issue by ButtonSmasher** [SkyrimTogether/issues-game#135]
I tried playing with around 6 players 2 were from AU 2 were from EU and other were from Africa and USA. Ping between Africa and EU is great, no problems noticed he could see me in normal animations all the time with no problems whatsoever.

AU and US have constant animations freeze and teleport all over the place for most of the time. No packet loss noticed, but they tend to bug out or completely crash out of nowhere.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the Server
3. Have players from EU and USA/AU connect to a EU host.
4. Animations Freezes or lag occurs

- This mostly happens with people above the 100+ ms. If you're USA and you're lower than 100ms most of the time they work fine.

## Reproduction rate

How many times can you reproduce it?
As many times as i want, as long the person has lag

## Expected result

Servers from EU and US/AU so they can play with each other and EU can stay with EU to not have lag.
Or
Stable connection fixes between EU and US/AU?

## Your environment
    * The Elder Scrolls V: Skyrim Special Edition

**Comment by Pokang** [comment]
There will be other servers locations in the near future which will make ping much better for non-EUs. 

Unfortunately though, we can't do much for lag between such locations that are extremely far from each other, the only thing we could do would be minimizing the impact of the lag, but we're no wizards, we can't make everyone have a good and fast connection to each other if they're this far...
Thank you for reporting the consequences of the lag though, we will try to look into it but I can't promise you you will ever be able to play with people that are so far with near to no negative impact on the game and the mod.

Closing the issue, but we'll still get this looked into, if we can do something to make it better we will try to.
