### ISSUE TITLE
Mods syncing for connecting players.

### ISSUE THREAD

**Issue by F1r3w477** [SkyrimTogether/issues-game#138]
## Description

Implement a way for players to join their friends and install the mods that their friends have on join. (p2p probably?) 

## Additional context

uwu

**Comment by Neusor** [comment]
Unfortunately we can't do that, (most) mod authors don't allow redistribution of there mods like that.

**Comment by SteamDosh** [comment]
` install the mods that their friends have on join`

Too much of a privacy issue hence why mod packs aren't really a thing unless you have author permission.

Closing.
