### ISSUE TITLE
Shield gone upon revival

### ISSUE THREAD

**Issue by robert15d** [SkyrimTogether/issues-game#139]
## Description

Lost shield after being revived and fought another player.

## Reproduction rate
Happened once.

## Expected result

Describe your expected result.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

**Comment by f13rce** [comment]
Will be looked into later, although a low priority for now as it isn't really game breaking. If you have more information, please provide them in this issue report.

**Comment by Pokang** [comment]
Reviving being very buggy, it has been removed as a whole, and you now load your latest save instead of going into a down animation. Therefore this bug does not exist anymore.
