### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by Enieu** [SkyrimTogether/issues-game#14]
## Description

As Rockhouse explained to me before, there's no way to save while connected to a session, so i spent some time thinking in how that could be solved.
what my idea consists is that when a player press F5, instead of simply quicksaving, he would be automatically disconnected, the game would create a new save (might be important, since skyrim saves are too unstable to rely in a single one) and reconnect him to the session again.
(and it should be good to edit skyrim auto save preferences to always off, so we don't get people fucking  up their saves).

**Comment by Evayr** [comment]
Saving has been fixed
