### ISSUE TITLE
The "ST" Chest

### ISSUE THREAD

**Issue by massdivide** [SkyrimTogether/issues-game#141]
##Desc
While shared loot is disabled, perhaps the ST team could enable a single loot container in the temple in whiterun to allow at least 1 spot to trade loot?

**Comment by Pokang** [comment]
Thank you for your idea, but someone on Discord pointed out a very easier and handy fix:

You can slightly trade stuff by having a friend equip an item (only equip-able items) open console click your friend and type “openactorcontainer 1".

Closing the "suggestion" as this should satsify your trading needs until we re-enable container sync!
