### ISSUE TITLE
Can't see the enemies of other players, who were killed by me before.

### ISSUE THREAD

**Issue by ProhorovIlja** [SkyrimTogether/issues-game#142]
## Description

Every time i'm fighting with the enemies, that my friend killed already, he's seeing me attacking a wall or an air.
Same stuff happens on my screen.
Goes with all the enemies in all possible locations.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Invite your friend and start a session.
4. Find any killed by your hand enemy and watch your friend attacking the air.

Attaching mine and my friend's dmp files. Since we played together:
https://drive.google.com/file/d/1WuT0timchUL3cW5YWTi8oDBIkHUGsvlC/view?usp=sharing (my friend's file);
https://drive.google.com/open?id=1abWhvPHg8mwtLy5IOqhr_prcKh8t9VQo (my dmp file).

## Reproduction rate

I can reproduce it every single time i'm playing with someone.

## Expected result

To see the enemies being dead for both of us, or visible for both of us, if someone didn't kill his enemy yet.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
      * Skyrim Together Mod

## Evidence (optional)

https://cdn.discordapp.com/attachments/275279982178205696/539148655786197012/unknown.png
This is a screen of the imperial guard, that is visible on my friend's screen, but completely invisible on mine.
But i can hear him saying something, when he was passing by me.

**Comment by ProhorovIlja** [comment]
https://cdn.discordapp.com/attachments/275279982178205696/539162118579290142/20190127205223_1.jpg
This is my pov on the position, where the guard should be standing for a both of us.

**Comment by f13rce** [comment]
I think this is fixed with the latest changes of the NPC synchronization. Please reopen this issue if it persists.
