### ISSUE TITLE
Flying corpse of a mammoth after fast traveling

### ISSUE THREAD

**Issue by ProhorovIlja** [SkyrimTogether/issues-game#143]
## Description

My friend saw a flying dead corpse of a mammoth from the ground once he fast traveled to a location with a mammoth symbol.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Invite your friend, launch a session.
4. Kill a mammoth, die afterwards.
5. Use /respawn command in a console to get respawned in a Shrine of Amara.
6. Fast travel to the mammoth location after that.

Attaching last dmp files:
https://drive.google.com/file/d/1WuT0timchUL3cW5YWTi8oDBIkHUGsvlC/view?usp=sharing
https://drive.google.com/open?id=1abWhvPHg8mwtLy5IOqhr_prcKh8t9VQo

## Reproduction rate

I believe, that it can be reproduced after fast traveling to the same location, where you killed a mob.
Pretty much all the times.
Since i saw some of a corpses moving on the ground then freezing on it.

## Expected result

To see corpses staying on the ground no matter what.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
      * Skyrim Together Mod

## Evidence (optional)

https://cdn.discordapp.com/attachments/275279982178205696/539148143149842452/20190127210057_1.jpg

**Comment by f13rce** [comment]
Will have a look later. Currently not really game breaking or anything, so will be put on the low priority list.

**Comment by Pokang** [comment]
Reviving being very buggy, it has been removed as a whole, and you now load your latest save instead of going into a down animation. Therefore this bug should not exist anymore.
