### ISSUE TITLE
Trader shopping window bug

### ISSUE THREAD

**Issue by ProhorovIlja** [SkyrimTogether/issues-game#147]
## Description

Every time i'm going into a trading menu of an NPC i can't go through categories on the left side of a screen or do anything until i'll press TAB button once.
So the info about my ping, pockets etc will show up.
Only after that i can access to the shop categories of a trader and my inventory.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Travel to any city and find a merchant or any NPC selling goods.
4. Start a dialogue.
5. Choose a selling goods question.
6. See that you can do nothing in this appearing menu until you'll press a TAB button once.

Attaching latest dmp file:
https://drive.google.com/open?id=1abWhvPHg8mwtLy5IOqhr_prcKh8t9VQo
https://drive.google.com/open?id=1fWFId8otnBmW_xbNzhg7B97qWoWecXHq
https://drive.google.com/file/d/1WuT0timchUL3cW5YWTi8oDBIkHUGsvlC/view?usp=sharing

## Reproduction rate

All the times i'm going into this menu.

## Expected result

To use a menu all the times without pressing any buttons to make it active.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
      * Skyrim Together Mod
## Evidence (optional)

https://youtu.be/00u9aZrag54

**Comment by Thesa22** [comment]
This is the same as issue #53, please close.
