### ISSUE TITLE
After getting respawned by a friend bug

### ISSUE THREAD

**Issue by ProhorovIlja** [SkyrimTogether/issues-game#148]
## Description

Sometimes after getting respawned by a friend, i'm staying on the ground lying.
And for me to stand up i need to mash space button in order to get up.
And after that i can't use a weapon until i'll switch to a first person view.
If i was in a 3rd person view when i got respawned.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Get killed by an enemy.
4. Allow your friend to res you.
5. Experience this bug with a chance( because sometimes it works fine).

Attaching latest dmp files:
https://drive.google.com/open?id=1abWhvPHg8mwtLy5IOqhr_prcKh8t9VQo
https://drive.google.com/file/d/1WuT0timchUL3cW5YWTi8oDBIkHUGsvlC/view?usp=sharing
https://drive.google.com/open?id=1fWFId8otnBmW_xbNzhg7B97qWoWecXHq

## Reproduction rate

Not every time, there is a chance of it to happen after getting resed.

## Expected result

Being able to move and use weapons every time after getting resed.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
      * Skyrim Together Mod

## Evidence (optional)

Don't have any evidence for this right now. 👎

**Comment by F1r3w477** [comment]
This has happened to my friend as well.

**Comment by f13rce** [comment]
Will have a look into it - I've seen it as well and it's indeed very annoying. :/

**Comment by Pokang** [comment]
Reviving being very buggy, it has been removed as a whole, and you now load your latest save instead of going into a down animation. Therefore this bug does not exist anymore.
