### ISSUE TITLE
Bug with getting respawned but immediatly hitted by an enemy and getting to the down state again

### ISSUE THREAD

**Issue by ProhorovIlja** [SkyrimTogether/issues-game#149]
## Description

My friend had a bug, when he was killed by a Whiterun Guard.
He went into a down state, waiting for a revive.
When he typed /respawn command in console he stud up with a half of hp.
But after getting attacked by a Guard he went into a down state with a 1hp again.
When he tried to type /respawn command again the console was sending a request a revive message or so. 
Saying, that he's not dead yet to be respawned again.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Got yourself downed by the enemy.
4. Make sure, that the enemy is still hitting your corpse.
5. Type /respawn command in console.
6. Get yourself respawned on the same place when you got downed by the enemy with a half of hp.
7. Enemy is attacking you again.
8. You're going into a down state again with 1hp.
9. Type /respawn command again and see an error message in a console.

Attaching latest dmp files:
https://drive.google.com/file/d/1WuT0timchUL3cW5YWTi8oDBIkHUGsvlC/view?usp=sharing
https://drive.google.com/open?id=1fWFId8otnBmW_xbNzhg7B97qWoWecXHq
https://drive.google.com/open?id=1abWhvPHg8mwtLy5IOqhr_prcKh8t9VQo

## Reproduction rate

Mostly all the times, when you're trying to get respawned, while your corpse is still getting attacked by an enemy.

## Expected result

To be respawned in a Shrine immediately without getting attacked by an enemy.
Or having a temporary invincibility to be able to travel to the Shrine without getting any dmg by an enemy.   

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
      * Skyrim Together Mod
## Evidence (optional)

Don't have an evidence for this bug, i'm sorry 👎

**Comment by Pokang** [comment]
There is indeed a small delay after a /respawn that I've noticed myself. Assigning this issue to the right person, thank you for reporting this.

**Comment by Pokang** [comment]
Reviving being very buggy, it has been removed as a whole, and you now load your latest save instead of going into a down animation. Therefore this bug does not exist anymore.
