### ISSUE TITLE
Vampire Lord

### ISSUE THREAD

**Issue by GoodLookingHarkon** [SkyrimTogether/issues-game#15]
## Description

Vampire Lord is still a bit of a problem. It either:
- crashes the player itself when he isn't the host.
- crashes other players when the vampire player is the host
- Works but is unable to transform back in the eyes of the other players. Your pants just disappear.

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition

* Mods used:

Skyrim Together
Elysium Estate

How many times can you reproduce it?

- I lost count.

## Steps to reproduce

This only occurs while the player is an actual vampire. If you add the vampire lord power using console commands it works fine.
So if you character is a vampire character and you transform, it will have one of the three results mentioned above.

## Actual result

Crashing or unable to transform back in the eyes of other players. 
![image](https://user-images.githubusercontent.com/35112510/34626453-faad3148-f25c-11e7-9523-50ccfe3b1785.png)

## Expected result

Being able to get in and out of Vampire Lord form without any issues.

**Comment by SteamDosh** [comment]
Is this still relevant?

**Comment by SteamDosh** [comment]
@WopsS For future we should make people include formIds of spells to reproduce bugs, 😴

**Comment by WopsS** [comment]
Do it.

**Comment by SteamDosh** [comment]
I don't know how to edit the template you [dew it](https://www.youtube.com/watch?v=BkIJsnLBA4c)

**Comment by WopsS** [comment]
https://github.com/SkyrimTogether/issues-game/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md edit and commit.

**Comment by SteamDosh** [comment]
Transform is fixed in https://github.com/yamashi/SkyrimOnline/pull/248
Other issues were fixed in some other builds
