### ISSUE TITLE
Crashing whenever fast traveling or saving

### ISSUE THREAD

**Issue by blntboi** [SkyrimTogether/issues-game#150]
This issues is preventing me from playing with friends. I can join they're party, I can meet up with them, but only if I walk to where they're at. I cannot enter buildings, save, fast travel, or teleport. If I do any of those actions listed I immediately crash and lose all my progress. Is there anything to do to fix this? I've already validated my files for SKSE and I didn't notice a change in anything.

**Comment by Pokang** [comment]
Deleting everything from the template and just writing 2 sentences is gonna make it totally impossible to reproduce.
Closing the issue.
