### ISSUE TITLE
Khajiit Racial

### ISSUE THREAD

**Issue by starbepthedroptip** [SkyrimTogether/issues-game#153]
Whenever I used the Khajiit nightvision it also applied to my nord friend

**Comment by Ueine** [comment]
its a known thing, basically all vision effects applies to all players.

**Comment by f13rce** [comment]
We cannot differentiate these type of effects over regular spells unless we check manually for formIDs. If we go with this approach, it will scale not well in regards to DLCs, mods, etc. Will not fix this issue.
