### ISSUE TITLE
Crash when entering Folgunthur.

### ISSUE THREAD

**Issue by TheRealJaSaMod** [SkyrimTogether/issues-game#155]
## Description

When you enter into Folgunthur just outside of solitude the game will put you through the loading screen and then crash.

Related formIDs|
---------------|
[Flames - 12FCD](http://en.uesp.net/wiki/Skyrim:Flames)|
[Nazeem - 1A6A4](http://en.uesp.net/wiki/Skyrim:Nazeem)|

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Enter Folgunthur.
3. Loading completed
4. Crash.

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.

## Reproduction rate

every time attempted

## Expected result

will crash when entered

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

Show us what happen.

**Comment by f13rce** [comment]
I think there's something wrong with the state of your game, as I fail to reproduce this. Although, this may have been fixed as switching cells triggers a saving mechanic, which should be fixed as mentioned here: https://github.com/SkyrimTogether/issues-game/issues/156

**Comment by f13rce** [comment]
Closing for now as this should be fixed in the next version of the mod. Please reopen it if you can reproduce it after the next update.
