### ISSUE TITLE
Flying and NoClip after being revived

### ISSUE THREAD

**Issue by LordBoos** [SkyrimTogether/issues-game#157]
## Description

Many times when I'm revived by a second player I "respawn" in a weird state where following issues occur:

1. When in 3rd person I still see my character dead on the ground
1. When I move it feels like my character is flying
1. My character has no collisions and I can fly through walls, ground and all objects, I can even get under the textures of the world or fly out of a dungeon to the "void"
1. I cannot turn my character using mouse and I can only "move" in the WASD directions

I can fix my character by fast traveling but it is a little annoying when in some long dungeon.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Get killed
4. Get revived by a friend

## Reproduction rate

Not sure exactly, but I'd say it's like 6/10 or 7/10 chance.

## Expected result

Be able to normally control my character after revival.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

No evidence yet but I could possibly record a video if needed.

**Comment by ButtonSmasher** [comment]
Press spacebar a few times, Go into 1st person, crouch or let your teammates kill you and be revived. I've had this too, most of the time a quick save reload does wonders. Hopefully this works for you otherwise get killed again and do /revive see if that works

- Note: Do not go to a different save while you're dead, this will mean you have to restart the whole game.

**Comment by f13rce** [comment]
Can you explain how exactly you died? This may have to do with what you're seeing.

**Comment by ButtonSmasher** [comment]
It happend with me when my party wasnt loaded in the cell. So it felt like i was in a completely different cell than them

**Comment by Boosik** [comment]
Happened to my in Skyrim when killed by a dragon. Also happened to me in Skyrim when died from a fall damage. Last time was in a dungeon when killed by some enemy magic.

**Comment by f13rce** [comment]
I have an assumption that this only happens when dying to fall damage. Can someone verify?

**Comment by Pokang** [comment]
Reviving being very buggy, it has been removed as a whole, and you now load your latest save instead of going into a down animation. Therefore this bug does not exist anymore.
