### ISSUE TITLE
No Connect Button and No Chat

### ISSUE THREAD

**Issue by famousfail** [SkyrimTogether/issues-game#161]
- Chat, Connect Button and Grouplist always invisible, cursor appears.

**Comment by Pokang** [comment]
If the ST interface does not open for you when you are in-game, by pressing Right Control, please follow these steps:

1. Close the launcher
2. Go to Steam/Steamapps/Common/Skyrim Special Edition
3. Delete the following file in the above named directory:
```v8_context_snapshot.bin```
