### ISSUE TITLE
Skyrim Together Menu Missing

### ISSUE THREAD

**Issue by Erithionis** [SkyrimTogether/issues-game#164]
## Description

When pressing right control the Skyrim Together menu does not show up

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Press Right Control

## Reproduction rate

Every Time

## Expected result

The Skyrim Together chat menu shows up

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition

**Comment by f13rce** [comment]
Hi, we've confirmed the issue alongside a temporary solution for now. Can you try deleting the v8_context_snapshot.bin file in the root directory of SSE and then relaunch Harbor? It should fix this problem.

**Comment by Erithionis** [comment]
> Hi, we've confirmed the issue alongside a temporary solution for now. Can you try deleting the v8_context_snapshot.bin file in the root directory of SSE and then relaunch Harbor? It should fix this problem.

That did fix it. Thanks

**Comment by Erithionis** [comment]
> > Hi, we've confirmed the issue alongside a temporary solution for now. Can you try deleting the v8_context_snapshot.bin file in the root directory of SSE and then relaunch Harbor? It should fix this problem.
> 
> My Skyrim is now crashing when I try to load up my world

Loading a previous save fixed the crashing

**Comment by ColonelCorn117** [comment]
Also make sure that you aren't using that key for anything else outside of Skyrim. I had an AutoHotKey script that used RCtrl to toggle my mic on/off, and the Skyrim Together menu would not show up until I changed/disabled the script.

**Comment by Pokang** [comment]
@ColonelCorn117 Unrelated, but you can assign global hotkeys directly in Discord to do that, you don't have to bother using AHK.
Closing the issue as it has been resolved, thank you for reporting!
