### ISSUE TITLE
Inability to wait 

### ISSUE THREAD

**Issue by CodeineZA** [SkyrimTogether/issues-game#167]
## Description
Cant wait when multiplayer. The world fast forwards but time does not pass.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Press T and try to wait.

## Reproduction rate
Infinite times

## Expected result

Time will not pass but the game's time does not pass.

## Your environment

 * The Elder Scrolls V: Skyrim Special Edition

**Comment by cesardmoro** [comment]
Any alternative to doing this ? i use the /time command but not working
