### ISSUE TITLE
Reviving player near benches and in hard to reach places

### ISSUE THREAD

**Issue by F1r3w477** [SkyrimTogether/issues-game#168]
## Description

Friend died in whiterun between a bench and a fire in one of the taverns, his tombstone was there, but it wouldnt let me revive him, it was like I wasn't close enough to revive him.  Tested it and it happened again.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Have friend die by bench
4. Try reviving

## Reproduction rate

Twice so far

## Expected result

Reviving

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition

**Comment by f13rce** [comment]
Was the UI saying you were trying to revive the player, or not even that?

**Comment by F1r3w477** [comment]
@f13rce Not even that. Wouldn't say I was reviving, wouldn't do the animation for it, he had to /respawn since I couldn't revive him.

**Comment by Pokang** [comment]
Reviving being very buggy, it has been removed as a whole, and you now load your latest save instead of going into a down animation. Therefore this bug does not exist anymore.
