### ISSUE TITLE
Shopkeeper bug

### ISSUE THREAD

**Issue by GoodLookingHarkon** [SkyrimTogether/issues-game#17]
## Description
EDIT: I just realised Ueine already made a report on this issue a month ago. It was fixed for a while (atleast I didn't notice) but it seems to be back. Feel free to close if not necessary anymore.

Unable to purchase from shopkeeper. I am able to open the "buying menu" after asking them what they are selling but I cannot see their goods nor an I click on weapons, apparel etc. etc. However, if I click, it seems to trigger their dialogue options. It's like their shop menu opens, but the game thinks you are still in the dialogue talking to him. You need to press "esc" and then it will work. It's almost like there's a hidden screen over it you have to close first.

## Your environment

Elder scrolls V: skyrim special edition.

* Mods used:
Skyrim Together
Elysium estate

## Reproduction rate

Every time I talk to a shopkeeper since the DLL evayr uploaded ~3 days ago?

## Steps to reproduce

Step 1: Talk to shopkeeper
Step 2: ask what they have to sell
Step 3: frantically click on their shop menu while having to listen to belethor and his story about how he would sell his sister in an instant.
Step 4: Press esc so you can finally purchase something

## Actual result

Unable to buy from shopkeepers the regular way. Having to press esc once to purchase.

## Expected result

Being able to see their items and to be able to buy without having to press esc.

## Evidence (optional)

Before pressing escape:
![screenshot81](https://user-images.githubusercontent.com/35112510/34696539-874c4f02-f4cf-11e7-91a2-c2674320162b.png)

After pressing escape: 
![screenshot83](https://user-images.githubusercontent.com/35112510/34696555-9062d872-f4cf-11e7-903d-67c9dbc187e8.png)

**Comment by AlexH-16** [comment]
Done, Should work for all relevant menus as well. Barter, container, gift, inventory, training.
