### ISSUE TITLE
Game Not Loading

### ISSUE THREAD

**Issue by N3stS** [SkyrimTogether/issues-game#182]
## My Game Won't Load

When trying to launch the game using the Harbor launcher there is an error saying "Loader is in the incorrect folder" and I don't know how to fix this issue.

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition

**Comment by Thesa22** [comment]
You have to have Special Edition. If you already do, the fix for this is in this post https://www.reddit.com/r/SkyrimTogether/comments/ajxkwr/all_known_fixes_for_issues_with_skyrim_together/

Please close.

**Comment by F1r3w477** [comment]
@N3stS for issues like this, you might want to go to the official discord and ask on there. There are many people (including myself) who are always on there to help others out.  https://discord.gg/skyrimtogether
