### ISSUE TITLE
Apocrypha (Black Book)

### ISSUE THREAD

**Issue by tomatoshiba** [SkyrimTogether/issues-game#184]
When I die in Apocrypha, I'm getting teleport back to the Black Book position and my body stuck outside of the dungeons and I've to type /respawn command.

![20190130233704_1](https://user-images.githubusercontent.com/46082108/52005114-792e9d00-24fb-11e9-880c-55abfa4ccab4.jpg)

**Comment by f13rce** [comment]
Please don't dismiss the template we've provided you to submit bug reports. It's very difficult/tedious now for us ti replicate this issue. Please reopen when you've updated your bug report.
