### ISSUE TITLE
a lot of issues in one

### ISSUE THREAD

**Issue by Recorpse** [SkyrimTogether/issues-game#189]
so basically... originally when my friend started using ST we joined a game together and it was fine so we left the sleeping giants in and we where both invisible to eachother so we tried rejoining each other but this time every time either of us hit launch his game crashed and froze on his screen. after that we spent a few days trying to make it work which we got it to work by doing a lot of thing like turning all of out mods off, making a new save, re installing the launcher MANY times. After a lot of issues his game started to crash to desktop and eventually after he got skse and a load of other stuff it started working. We then saved our games and came back on the next day. we both loaded up our save games fine but when we tried launching the server again it crashed, so he tried loading his game up again and it crashed before he could even click launch. He then tried a few more times after that and it just kept crashing sooner an sooner to the point in which he couldn't even walk 2 steps without the game crashing.
You still here? probably not.
so after that he tried loading up normal sse and the same thing was happening even without ST active and on a totally normal save game. so he deleted his two save files that were from ST and his game worked fine with his old saves unlike it was before when he had the two ST save files.
at this point its just annoying and no one on the discord server can help. What makes it worse is that the #questions isn't open.

please for the love of god tell me whats happening here.

**Comment by F1r3w477** [comment]
1. Please follow the formatting for the bug reports list. A big wall of text like this is exceptionally hard to read and takes away time from the devs (They are forced to interpret what you type). This report most likely will be ignored until formatting is changed unless a dev feels like wasting time.

2. For multiple bugs, we need multiple reports.

3. The #questions channel gets closed on discord when there aren't enough people online to be able to answer the questions in there. #discussion is always open and there are lots of people (including myself) who answer questions in there.

**Comment by Recorpse** [comment]
this is not multiple bugs its multiple issues. I don't even know if you could call it a bug. And if the devs want to improve what they are working on then they will spend the time reading this. this is  the best way I could think of to describe the issue we are having. this as much a dev issue as it is my own issue. this is the devs work after all and if issues like this can't be read and fixed within the program itself then it isn't going anywhere. Also I was told to post the issue here I was not told of any format I needed to submit the issue in. either sort this issue out in your program or you can expect to get no more support from anyone I know as from what I know this isn't an issue on my friends side it is an issue on the devs side. its not my responsibility to help the devs with there problems but im giving them this info anyway to help that they improve upon these issues for future users of ST. I hope you and the devs can understand that. frankly im sick of all of this. I've asked for help many times and i've received almost no help. from the devs or the mods on the discord server.

**Comment by Recorpse** [comment]
and you're welcome for another bit wall of text. maybe the devs will learn that it isn't easy dealing with developing something like this on more than just a development standpoint but also from the users. no one said it would be easy and also it isn't my responsibility to make it easy. they got themselves into this when they released the thing.

**Comment by f13rce** [comment]
There's a couple of things missing with this report:

1: The basic template we'd *really* like you to fill in, so it makes our job easier to make a better functioning mod
2: Crash and dump reports
3: A nice (or at least neutral) attitude towards the community

Since your explanation is really vague with little to no extra info to work with, I will close this issue and will ask you to remake any issue you encountered as a new issue where you follow the template. Alternatively, look for issues that seem similar to the ones you're having right now and try to complete them to the best of your knowledge.

**Comment by Recorpse** [comment]
@F1r3w477 I explained this in as much detail as possible that is why its so damn long.

**Comment by Recorpse** [comment]
i literally told you everything I know about what happened and all of the info I know of
what else do you want me to put here? also I was nice to the community for the first 3 days I was having this issue but if i'm going to keep getting nothing in return for being nice then im not going to be

**Comment by Recorpse** [comment]
also I can't give you the crash report as like I said it is my friend who is having the issue

**Comment by f13rce** [comment]
I'll just leave this here for your friend to review: https://old.reddit.com/r/SkyrimTogether/comments/ajxkwr/all_known_fixes_for_issues_with_skyrim_together/

**Comment by Recorpse** [comment]
already looked through it 10 times

**Comment by Recorpse** [comment]
both of us. didn't help

**Comment by Recorpse** [comment]
@F1r3w477

**Comment by f13rce** [comment]
Without any dmp files I cannot do anything, as the description is still too vague. Please tell your friend to either upload it here or give it to you so you can upload it here.

**Comment by F1r3w477** [comment]
@Recorpse A fun thing some of us have done on the discord is pretend the Mods a figment of our imagination. They are there to keep order. The Community Helpers (Gold names) are there to help people more. The 2364 people on right now with the green names, also help out as best as they can. Feel free to ping me on the server if you need any help ( ItsDan#6969 ) or message me directly if you want.
