### ISSUE TITLE
Dropping Items as Cell Host Disappears

### ISSUE THREAD

**Issue by Logickane** [SkyrimTogether/issues-game#195]
## Description

Just tested dropping items, works partially. As the cell host I could see and pick up items that were being dropped by other player. But whenever I dropped something it disappeared before it hit the ground. Also the other player did not see the item on the ground.
 
## Steps to reproduce

1. Start the game.
2. Connect to the server.
3. Connect to another player.
4. As the cell host, drop an item and watch it disappear.

## Reproduction rate

Tested once, got what you read in the description.

## Expected result

As cell host, items would fall to ground and not disappear and non-hosting player could pick it up.

## Your environment

The Elder Scrolls V: Skyrim Special Edition
No SKSE or Mods
Other player just had SKSE

**Comment by f13rce** [comment]
Was it a stack of items, or a multiple of one item that was dropped? (Like dropping 6 shields at once instead of one-by-one)

**Comment by Logickane** [comment]
It was just single items, tried a potion that the other player had just dropped, and few pieces of armor. Everything I dropped disappeared.

**Comment by Logickane** [comment]
Will re-open this when the feature is re-activated, and if bug still persists.

**Comment by Wanheda1** [comment]
Have the same problem
