### ISSUE TITLE
Invalid email and/or password

### ISSUE THREAD

**Issue by Inevy** [SkyrimTogether/issues-game#197]
## Description

When I try to log in it says it's invalid. I tried making 3 accounts with different email/password but still can't login.

## Steps to reproduce

How to reproduce this issue:

1. Open harbor.
2. Try to log in.
3.Invalid email and/or password.

## Reproduction rate

How many times can you reproduce it?

5/5

## Expected result

Describe your expected result.

Log in.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)

Show us what happen.

https://gyazo.com/1c7b49af543b4e757f1b30502fc3271e

**Comment by CoursePS** [comment]
Have you tried logging back onto the website? Does that work for you?
If you can log onto the website but you can't log into Harbor, your accounts will need to be reset.
However, it's odd that you're having this issue on multiple, fresh accounts.
If you can't log back into the website either, you must've made a mistake in the registration process. But even that seems unlikely after creating 3 accounts.

Please let us know if you're still having problems. And let us know what happens after trying the above.

**Comment by Inevy** [comment]
I can log log in the website. And I've checked the files. The download came
with a few missing files but I messed with the files a little and I can log
in now.

**Comment by Pokang** [comment]
Wrong issueboard, and the issue isn't relevant anymore.
