### ISSUE TITLE
Spell Casting not ending on other players games.

### ISSUE THREAD

**Issue by Gamepaw** [SkyrimTogether/issues-game#20]
## Description

Spells not turning off/being deactivated. Example, P1 is using Lightning Storm, P2 sees this, P1 Stops using spell, P2 still sees spell activating.

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition

## Reproduction rate

Can be reproduced, unsure how. Happens randomly.

## Steps to reproduce

N/A happens on random occasions and sometimes not all with a play-through.

## Actual result

Spell continues firing and hits everything and everyone.

## Expected result

Spell turns off.

## Evidence (optional)

https://clips.twitch.tv/FrozenTolerantDolphinMau5

**Comment by SteamDosh** [comment]
may be a new animation we aren't catching, what spell was being casted?

**Comment by Gamepaw** [comment]
The spell that was being cast was the Destruction spell Lightning Storm -
http://elderscrolls.wikia.com/wiki/Lightning_Storm_(Skyrim)

Recasting it didn't cause it to stop, however switching to another
item/spell did stop it.
It sometimes stops but other times it does not, is strange. Maybe something
with casting length or something.

**Comment by Gamepaw** [comment]
The spell that was being cast was the Destruction spell Lightning Storm - http://elderscrolls.wikia.com/wiki/Lightning_Storm_(Skyrim)

Recasting it didn't cause it to stop, however switching to another item/spell did stop it.
It sometimes stops but other times it does not, is strange. Maybe something with casting length or something.

**Comment by Evayr** [comment]
Is this still a problem?

**Comment by Gamepaw** [comment]
Yes.

**Comment by Gamepaw** [comment]
Gif version of this issue. 

Two Handed - Lightning Storm - Doesn't cancel after being cast, can be cancelled by caster if they switch to other spells. https://i.imgur.com/cdVUmOK.gifv

**Comment by SteamDosh** [comment]
@Gamepaw make a seperate issue for that, include the spell formID so I can replicate it myself

**Comment by Gamepaw** [comment]
@SteamDosh https://github.com/SkyrimTogether/issues-game/issues/41

**Comment by SteamDosh** [comment]
Should be more reliable now, still needs minor improvement however leaving this issue open for now
