### ISSUE TITLE
Crash when transitioning into Cronvangr Broodlair

### ISSUE THREAD

**Issue by mienamoo** [SkyrimTogether/issues-game#209]
## Description

When transitioning into Cronvangr Broodlair, the game crashed.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Create character with alternative start.
3. Connect to the server.
4. Enter Cronvangr Cave.
4. Transition into Cronvangr Broodlair.
5. Crash.

## Reproduction rate

Happened once so far.

## Expected result

Transition into new area and don't crash.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)

See dmp file attached.

[09b3e067-a37f-46f6-ab6e-ded9646b38ce.zip](https://github.com/SkyrimTogether/issues-game/files/2825610/09b3e067-a37f-46f6-ab6e-ded9646b38ce.zip)

**Comment by mienamoo** [comment]
Seems to be resolved in the latest build. Haven't had any crashes yet. :)

**Comment by f13rce** [comment]
Thank you for the update! Don't forget to reopen this if it still occurs :)
