### ISSUE TITLE
Missing Sword.

### ISSUE THREAD

**Issue by Gamepaw** [SkyrimTogether/issues-game#21]
## Description

A short description about your issue or detailed description for a feature request.

## Your environment
    * The Elder Scrolls V: Skyrim Special Edition

## Reproduction rate

N/A

## Steps to reproduce

N/A

## Actual result

No Sword appearing on screen.

## Expected result

Sword appears.

## Evidence (optional)

https://clips.twitch.tv/ColorfulLongOwlSSSsss
https://clips.twitch.tv/MoistDullHawkSoBayed
https://clips.twitch.tv/CalmHelpfulCarabeefPMSTwin

**Comment by SteamDosh** [comment]
Crash was probably unrelated to attacking the shield, (is handled natively by skyrim)

Weapon however can be looked into by @Evayr

**Comment by Evayr** [comment]
May be fixed with the container bugfixes.

**Comment by Evayr** [comment]
Should be resolved since we add the item to the container before equipping it.
