### ISSUE TITLE
"YOU DO NOT HAVE ACCESS TO THE CLOSED BETA"

### ISSUE THREAD

**Issue by jacamojk** [SkyrimTogether/issues-game#211]
/---/ * Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

/---/ * Operating system (choose one):
    * Windows 10 x64

/---/ WHAT I DONE:
 i have followed all steps to install and qualify for the skyrim together mod. (i installed skyrim special edition, become a patreon and confirmed $1 pledge, registered with skyrim together website, linked patreon with skyrim together account and downloaded harbor launcher)

/---/ PROBLEM:
when i try to log in on the Harbor launcher it says "you do not have access to the closed beta" 

/---/ NOTE:
before i started the whole proccess to install skyrim together i bought fresh a copy and installed skyrim special edition a clean install no mods or anything . few hours later... i have installed basic performance mods and it still doesnt work.

**Comment by Claxicorn** [comment]
This is on Patreons end not ST's, or yours. Its been happening for the past two days or so.

**Comment by cikeZ00** [comment]
Would appreciate if you closed this issue.
As the person above said, its a Patreon issue, doesnt have anything to do with ST.

**Comment by jacamojk** [comment]
thanks for the reply, maybe i should leave it  up just in case someone else like me comes along and needs answers.

**Comment by Claxicorn** [comment]
It is all that is being talked about on the Discord, the subreddit and twitter, so i believe they will be okay.

**Comment by jacamojk** [comment]
i only just found out from here and have been trying to figure it out over 3 hours now, pretty frustrating when you just bought a copy especially to play today, im not complaining but theres bound to be people who havent seen reddit or twitter who will benefit from seeing this conversation.

**Comment by F1r3w477** [comment]
@jacamojk Please close this issue.

**Comment by F1r3w477** [comment]
Especially considering your other one related to the same thing was closed :)

**Comment by SteamDosh** [comment]
Contact a dev on discord and they'll sort it out. 
Blame is on patreons end.
