### ISSUE TITLE
Visual zooming in/out when using the wheel in the inventory menu

### ISSUE THREAD

**Issue by xNicklaj** [SkyrimTogether/issues-game#213]
## Description

Title says it all

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Open menu.
3. Scroll with the wheel.

## Reproduction rate

Everytime

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 10 x64

**Comment by DrxWorm** [comment]
I believe this is happening because they disabled the menu pause function to prevent the game from pausing when one player of the group enters the menu. so there is a disconnect between in game and menu scroll wheel functionality. i'm not really sure how they can work around this, but i believe that is the issue.

**Comment by almanzarsaul** [comment]
> I believe this is happening because they disabled the menu pause function to prevent the game from pausing when one player of the group enters the menu. so there is a disconnect between in game and menu scroll wheel functionality. i'm not really sure how they can work around this, but i believe that is the issue.

They already have the solution for it. This bug happened to be and its only when opening a menu directly like "I" for inventory or "J" for journal. This does not happen when you press "Tab" for the 4 arrowed menu, this is just an overlook by the devs, as regular Skyrim pauses when in menus they just locked the scroll wheel lock after pressing Tab. They just need to implement that to all the other menu buttons.

**Comment by almanzarsaul** [comment]
I have attached a gif to bettter show the bug for the devs. _When searching a corpse the same effect happens._
![scroll_pov](https://user-images.githubusercontent.com/32269428/52447303-61a87300-2afe-11e9-8b3e-a7ff23e5bc86.gif)

**Comment by Pokang** [comment]
This should not be an issue anymore, since we removed the no pause code, that makes it in line with other menus. Please reopen if it occurs other issues with sync or the mod in general.
