### ISSUE TITLE
Opening a seller container keeps the npc dialogue in background

### ISSUE THREAD

**Issue by xNicklaj** [SkyrimTogether/issues-game#214]
## Description

When opening a market container (Tested on riverwood NPCs) via dialogue the dialogue will get stuck in the background and to access the buy interface I need to press esc to close the dialogue (Which is anyway hidden under the visible menu) and then I can interact with the buy/sell menu.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Speak with a commercial NPC.
3. Open its sell container.

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.

## Reproduction rate

Everytime.

## Expected result

Describe your expected result.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)

Show us what happen.

**Comment by SteamDosh** [comment]
varient of #53
