### ISSUE TITLE
Unsynchronized NPCs (especially guards)

### ISSUE THREAD

**Issue by Sorimachi** [SkyrimTogether/issues-game#215]
## Description

Playing as guest, many times when I was fighting, the host was unable to see what I was fighting. This was especially an issue when a Whiterun guard attempted to arrest me.
No dialog appeared, and he assumed I was resisting arrest. He swiftly killed me, and the host resurrected me. The dialog to surrender appeared. I ended up in jail and was promptly killed again for attempting to escape. The host came to rescue me, but was unable to see my gravestone or the 4 guards attempting to kill my corpse. I eventually timed out and was put resurrected in the Temple of Kynareth

## Steps to reproduce

How to reproduce this issue:

1. Play with friends

## Reproduction rate

How many times can you reproduce it?

## Expected result

Describe your expected result.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)

Show us what happen.

**Comment by f13rce** [comment]
Is fixed in next patch :)
