### ISSUE TITLE
Looping dead/alive and loading screen if killed when travelling through doorway

### ISSUE THREAD

**Issue by WhiskeyHorse** [SkyrimTogether/issues-game#216]
Decided to loot at the Riverwood inn after starting my adventure there with Alternate Start Mod, and got caught stealing. Fled through the door, but was slain while going through the door, as the game doesn't pause. Ended up on a looping screen where my character stays still and unmovable. It loops the following:
Get hit once by the two innkeepers and hear the sound of death (no actual animation), game loads last autosave (Going through the door, starting the process over.)
I couldn't leave the group or respawn since it kept going to the loading screen every few seconds, I had to Alt+F4.

**Comment by Neusor** [comment]
Hi,
Please follow the template which can be found here : 
https://github.com/SkyrimTogether/issues-game/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by SteamDosh** [comment]
Open a new issue with the correct format.
