### ISSUE TITLE
JOIN FRIEND THEN CRASH

### ISSUE THREAD

**Issue by jacamojk** [SkyrimTogether/issues-game#217]
me and 2 friends, clean installed, removed all mods, started new game, new character, was at the same point in terms of story quests events etc.. but we still crash wen i join, but they can join eachother?? is there anything im missing here??

**Comment by Thesa22** [comment]
Hi,
Please follow the template which can be found here :
https://github.com/SkyrimTogether/issues-game/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md
