### ISSUE TITLE
Missing Spell Animation.

### ISSUE THREAD

**Issue by Gamepaw** [SkyrimTogether/issues-game#22]
## Description

A short description about your issue or detailed description for a feature request.

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition

## Reproduction rate

N/A

## Steps to reproduce

N/A

## Actual result

No animations for casting of spells on other players, in video it shows neither getting a proper animation, however before the double handed spell animation did appear. 

## Expected result

Casting animations to play for both one handed and two handed spells.

## Evidence (optional)

https://clips.twitch.tv/BlindingFurryShallotAliens

**Comment by SteamDosh** [comment]
Casting has been implemented and properly used, refer to #28 for 2H spell casting
