### ISSUE TITLE
Friends can't see my dropped items

### ISSUE THREAD

**Issue by Whitermale** [SkyrimTogether/issues-game#232]
## Description
Dropping items for other players to pick up do not show on other player screen. Same goes for me when a friend drops an item.

## Steps to reproduce

1. Start the game.
2. Connect to the server.
3. Join a friend.
4. Drop an item.
5. Friend does not see the item.

## Reproduction rate

Infinite times, never seen a friends' item drop.

## Expected result

Dropped item to be visible for me/friend.

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 10 x64

**Comment by Teller22** [comment]
From the recent update:
- Disabled container-related sync (chests and dropping items) until it is more tested and polished
