### ISSUE TITLE
Friendly fire issue

### ISSUE THREAD

**Issue by Hackadactyl** [SkyrimTogether/issues-game#235]
We've been playing in a group of 5, everyone on legendary, and we discovered a small issue with friendly fire. Im not saying it should be turned off but in a big fight especially in closed quarters its very hard to distinguish bandits from players, i think players should have some sort of a marker above their heads or their nickname. But the main issue is that while we tried to fight between ourselves we did normal amounts of damage, but when fighting in bleak falls barrow i accidentally sprayed a basic fire spell on my friend, just for a split second and he almost INSTANTLY died. I watched his health go down by 3/4 after an accidental touch of fire. I dont think it works as intended. 

## Steps to reproduce

1. Connect to a player. 

2. Make sure all players have their difficulty set on legendary. 

3. While fighting bandits, use the basic fire spell, target it on the enemy and try sliding it onto another fighting player for a second.

## Reproduction rate

Havent been tested enough times to tell how often it happens, the issue was spotted accidentally. 

## Expected result

Player melee fighting with the npc while razed with the fire spell dies very quickly

## Your enviroment 

Windows 7 64x
The Elder Scrolls: Skyrim Special Edition

**Comment by Hackadactyl** [comment]
I cannot fully expand on the issue now, i will test it again today.

**Comment by SteamDosh** [comment]
Damage is dependent on your difficulty, I would assume this is your issue.

**Comment by Hackadactyl** [comment]
I know that, but the player shouldnt die after one touch of fire while i can burn an npc for 10 seconds and it will do almost nothing to him.

**Comment by SteamDosh** [comment]
Without anything to debug or to look at this will be closed.
