### ISSUE TITLE
Opening st ui with rightctrl makes the character run infinitely

### ISSUE THREAD

**Issue by xNicklaj** [SkyrimTogether/issues-game#241]
## Description

Opening skyrim together's UI while walking will make the character run infinitely. No matter where you move, when you remove your finger from a key it will keep running towards the horizon.
Most of the times you need to reload to fix this

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Load a save
3. Walk and press right ctrl.
4. Press rightctrl again and look at your character go towards the infinite

## Reproduction rate

100%

## Expected result

1. Start the game
2. Load a save
3. Walk and press right ctrl.
4. Character stop there and then

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)

Show us what happen.

**Comment by CoursePS** [comment]
I'm quite sure this can be fixed by simply pressing the key of the direction your character is walking in again. You shouldn't have to reload to fix this.
