### ISSUE TITLE
Steam not allowing ST to launch

### ISSUE THREAD

**Issue by Zombiesniper540** [SkyrimTogether/issues-game#243]
## Description

A clear and concise description of what the bug is, Include any formIDs relevant for us to use ie,

Related formIDs|
---------------|
Carmine's friend
Discord:Carmine#9985

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Interruption with message from steam

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.
None
## Reproduction rate
100%
How many times can you reproduce it?
Inf
## Expected result
Not able to launch skyrim together
Describe your expected result.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 7 x32
    * Windows 7 x64
    * Windows 10 x32
    * Windows 10 x64
Unknown

**Comment by Zombiesniper540** [comment]
I did this for Carmine but I don't have any more info that what I gave contact him for more info.

**Comment by Pokang** [comment]
This is what happens when you launch ST without having Steam opened beforehand or when you have weird Windows perms.
In the latter case, start our launcher as admin.
