### ISSUE TITLE
Crash whenever entering new cell.

### ISSUE THREAD

**Issue by SMZFaustus** [SkyrimTogether/issues-game#244]
## Description

I crash whenever I enter a new cell, even if I'm not connected to anyone. Everything else seems to work fine, but I'm essentially restricted to whatever cell my save was located in. I've tried loading old saves, using Win 7 compatibility mode, and running as admin, nothing seems to work. New saves also crash upon entering a new cell, so I can't even start over. When starting Skyrim through Steam, the game works perfectly, this only happens when I launch with Harbor. This only recently started happening, the mod used to work very well.

## Steps to reproduce

1. Launch with harbor
2. Load save
3. Exit cell
4. Crash.

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.

[0d6b60df-a387-44ce-bfc2-94f4c7ced257.zip](https://github.com/SkyrimTogether/issues-game/files/2848555/0d6b60df-a387-44ce-bfc2-94f4c7ced257.zip)

## Reproduction rate

100% of the time.

## Expected result

Load into another cell w/o crash.

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):

    * Windows 10 x64

**Comment by SteamDosh** [comment]
Our code shouldn't be causing crashes until you are in a server with another player, sounds more like a save file corruption - try a new save and change cell.

**Comment by SMZFaustus** [comment]
> Our code shouldn't be causing crashes until you are in a server with another player, sounds more like a save file corruption - try a new save and change cell.

I ended up fixing it by completely uninstalling and reinstalling ST. I'm guessing the issue was some weird anomaly or a conflict of some kind since I haven't seen it happen to anyone else.
