### ISSUE TITLE
Revive bug after being tossed with a Fus-Ro-Dah off the cliff and revived with a tombstone

### ISSUE THREAD

**Issue by ProhorovIlja** [SkyrimTogether/issues-game#246]
## Description

I was playing with my friend, we came from Riverwood, killed a scripted wolf and after that he told me to stand on a cliff, so he can fus-ro-dah me away from it.
After he launched me from that cliff, my health went to 0 and i went into a downed state laying on the ground.
After that happened my friend saw a tombstone next to me, he did interact with it and i got my health back still laying on the ground in the same pose, but unfortunately i couldn't move at all.
All the buttons i pressed on my keyboard didn't make my character to stand up or do anything else.
The only thing i could control was a camera.
My friend told me, that on his screen he saw my character constantly falling on the round in a loop then standing back up and falling once again.
All that was going in a loop.
While i saw my corpse laying on a ground with no movement at all.
When i've opened a console and type /respawn it told me, that i've alive so the command wouldn't work.
You can see it all in a video, i attached to this bug report ticket in the end with a link.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Come to a cliff after a scripted wolf in Riverwood with a friend.
4. Let your friend to Fus-Ro-Dah your character off that cliff.
5. Wait for your character to get a downed message on console.
6. Let your friend to res you with a tombstone.
7. Try to move after you'll see your life bar being restored.(nothing will happen)

No dmp files were created after my session with a friend.
I did crash to desktop a few times, but an overall no dmp files i or my friend have after our playthrough.

## Reproduction rate

I guess, that it is pretty random, so i would say a few random times.
It doesn't look like a constant bug to me.

## Expected result

To see a revive mechanic working all the time as intended with my character standing up and being able to move and attack.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    * Skyrim Together Mod (Harbor)
    
 * Operating system (choose one):
    * Windows 7 x64(my friend using)
    * Windows 10 x64(i'm using)

## Evidence (optional)

https://youtu.be/cVi2XFaWVhg

**Comment by f13rce** [comment]
Thank you. Will look into this.

**Comment by Pokang** [comment]
Reviving being very buggy, it has been removed as a whole, and you now load your latest save instead of going into a down animation. Therefore this bug does not exist anymore.
