### ISSUE TITLE
Closes on the loading screen

### ISSUE THREAD

**Issue by Guibrandao01** [SkyrimTogether/issues-game#250]
## Description

my skyrim closes on the loading screen

## Steps to reproduce

How to reproduce this issue:

1. Start the launcher.
2. Connect login.
3. Started Play
4. clicked on button play
5. loading screen
6. Game closes alone after time

## Reproduction rate

How many times can you reproduce it?
oftentimes

## Expected result

Describe your expected result.

## Your environment

* Launcher version: 1.5.62

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):

    * Windows 7 x64
  

## Evidence (optional)

I start the game, in the loading screen after a while the game closes

**Comment by Pokang** [comment]
Try launching your game through Steam to change the video settings, and set the game to borderless windowed, let me know if that fixes it.
