### ISSUE TITLE
Habor cannot launch the game

### ISSUE THREAD

**Issue by Dalto1** [SkyrimTogether/issues-game#253]
## Description

I cannot launch the game via Harbor. I've reinstalled the game several time and still cannot launch the game. I've try to save, start a new game and load a game but the game isn't starting.

## Steps to reproduce

I dont know how to reproduce the bug. My game was working fine 2 weeks ago and i cannot launch the game via Harbor since this week. Even fresh install are not working

## Reproduction rate

Infinite times

## Expected result

Launching via harbor : terminal is quitting. The game seems to be starting when i check the steam app library but there isnt nothing appening.

## Your environment
    * The Elder Scrolls V: Skyrim Special Edition
    * Windows 10 x64

## Final checks for the reporter
- [ X] I have browsed through the other issues and confirmed that this issue has not been reported already
- [X ] I made sure that I have applied the template for my bug report

**Comment by HavocxPro** [comment]
Exact same problem here

**Comment by Pokang** [comment]
This should not be an issue anymore, please try disabling Windows Defender temporarily to see if that fixes it.
If it doesn't, feel free to reopen the issue with further info.
