### ISSUE TITLE
Auto Correct disable

### ISSUE THREAD

**Issue by SteamDosh** [SkyrimTogether/issues-game#26]
## Description

Automatic filling and correction of form controls is enabled.

## Actual result

When the user types into specific form fields, the browser suggests previously entered values.

## Expected result

The browser's suggestions should not appear.

**Comment by Dumbeldor** [comment]
Not reproduced on the search field and on the connection to an server with an IP.
I think the problem is solved and we can close this issue.

**Comment by Gamepaw** [comment]
Reproduced. May be only close spelling mistakes are detected or based on Default Language.
English - 'Chiar' instead of 'Chair' caused a red line in text chat and in search box, however not on IP.

**Comment by Dumbeldor** [comment]
Fixed on my branch ui_groups_fix.
Waiting for the merge of my branch on rework to close the issue.

**Comment by Dumbeldor** [comment]
i fixed that, so i close ;)
