### ISSUE TITLE
Cheat to gain Armor levels

### ISSUE THREAD

**Issue by MrChickenWingz** [SkyrimTogether/issues-game#263]
## Description

Train armor while down

Related formIDs|
---------------|

## Steps to reproduce

How to reproduce this issue:

1. Die
2. Have something attack you that does a lot of damage (Giant)

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.

## Reproduction rate

How many times can you reproduce it?
when i die

## Expected result

gained armor

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)

Show us what happen.

## Final checks for the reporter

- [ X] I have browsed through the other issues and confirmed that this issue has not been reported already
- [ X] I made sure that I have applied the template for my bug report

**Comment by Pokang** [comment]
Reviving being very buggy, it has been removed as a whole, and you now load your latest save instead of going into a down animation. Therefore this bug should not exist anymore.
