### ISSUE TITLE
Non-host cant sell or buy with merchants

### ISSUE THREAD

**Issue by ThatSirOnTheLeft** [SkyrimTogether/issues-game#265]
## Description,
Non-Host can not sell or buy with merchants. It happened twice for us for only 2 merchants we talked to (Blacksmith in riverdale and Khajiit caracan outside whiterun) we havent tested to see if its cause we accessed them at same time or not. 

Related formIDs|
---------------|
[Flames - 12FCD](http://en.uesp.net/wiki/Skyrim:Flames)|
[Nazeem - 1A6A4](http://en.uesp.net/wiki/Skyrim:Nazeem)|

## Steps to reproduce

How to reproduce this issue:
1. Start the game.
2. invited friend
3.talked to merchant
**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.

## Reproduction rate

How many times can you reproduce it? twice

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 

- [ ] I have browsed through the other issues and confirmed that this issue has not been reported already
- [ ] I made sure that I have applied the template for my bug report

**Comment by Dragonisser** [comment]
Already known. 

[SkyrimTogether/issues-game#53](https://github.com/SkyrimTogether/issues-game/issues/53)
[SkyrimTogether/issues-game#104](https://github.com/SkyrimTogether/issues-game/issues/104)
[SkyrimTogether/issues-game#147](https://github.com/SkyrimTogether/issues-game/issues/147)
[SkyrimTogether/issues-game#214](https://github.com/SkyrimTogether/issues-game/issues/214)
[SkyrimTogether/issues-game#262](https://github.com/SkyrimTogether/issues-game/issues/262)
