### ISSUE TITLE
Crashing when trying to save

### ISSUE THREAD

**Issue by Darkalll** [SkyrimTogether/issues-game#266]
## Description

A clear and concise description of what the bug is

when i try to save the game, it keeps crashing , even with older saves

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Trying to save
3. Crash.

[d6b3681a-c64b-4c9a-a218-0c87d41b3a63.zip](https://github.com/SkyrimTogether/issues-game/files/2891054/d6b3681a-c64b-4c9a-a218-0c87d41b3a63.zip)

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.

## Reproduction rate

every time

## Your environment

* Game edition (choose on which edition do you have problems):

    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
  

    * Windows 7 x64
 

## Final checks for the reporter

- [ ] I have browsed through the other issues and confirmed that this issue has not been reported already
- [ ] I made sure that I have applied the template for my bug report

**Comment by Darkalll** [comment]
and it seems to match with the fact that my Mod Organizer 2 not launching anymore when i added Skyrim together Launcher

**Comment by SteamDosh** [comment]
Duplicate #156
