### ISSUE TITLE
The UI allows for opening the context menu

### ISSUE THREAD

**Issue by skreborn** [SkyrimTogether/issues-game#27]
## Description

The UI allows for opening the context menu.

## Steps to reproduce

Right click to open the browser's context menu.

## Actual result

The context menu opens, and the user is allowed to click on its items.

## Expected result

The context menu shouldn't appear.

**Comment by Dumbeldor** [comment]
Fixed with the update of CEF

**Comment by SteamDosh** [comment]
This was fixed by me you frenchie

**Comment by Dumbeldor** [comment]
seriously ? I thought it was @WopsS

**Comment by Dumbeldor** [comment]
Good Job Dosh :wut:
