### ISSUE TITLE
Revived Player Remains in Downed Position Until Jumping

### ISSUE THREAD

**Issue by Erithionis** [SkyrimTogether/issues-game#270]
## Description

When a Player is revived they remain on the downed position on their screen (but stand up normally for other players). Once the revived Player jumps they return to normal gameplay animations, but before this they are unable to move or attack. This occurred within Bleak Falls Barrow near a staircase,w hcih may have a factor do with it.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Have a Player die (if possible, on an uneven surface)
4. Revive Player
5. If Player remains downed on their screen, jump.

## Reproduction rate

Once

## Expected result

PLayer returns to normal gameplay animations after revival with no need to jump

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system
    * Windows 10 x64

## Final checks for the reporter

- [x] I have browsed through the other issues and confirmed that this issue has not been reported already
- [x] I made sure that I have applied the template for my bug report

**Comment by Pokang** [comment]
Reviving being very buggy, it has been removed as a whole, and you now load your latest save instead of going into a down animation. Therefore this bug does not exist anymore.
