### ISSUE TITLE
Harbor Loader is in incorrect folder

### ISSUE THREAD

**Issue by Mulras** [SkyrimTogether/issues-game#271]
## Description !Loader is in incorrect folder and how to fix it!

A clear and concise description of what the bug is, Include any formIDs relevant for us to use ie,
this only happens after verify and update and when you click play you get the Loader is in incorrect folder... i might have installed it wrong one time and then it would not let me install it the right way when i found out i did a mistake. i think that is the case here. the reason in small terms is it could not find its way back to SSD C and keept on putting the game at harddrive D

How to reproduce this issue: put your game in SSD C and the Harbor in SSD D

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.

## Reproduction rate 100% fail rate

How many times can you reproduce it? i could redownload it all and it would still happen.

## Expected result

Describe your expected result.

## Your environment 

* Game edition  * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choo   * Windows 10 x64se one):

## Evidence (optional)

Show us what happen.

## how to work around the bug.Open RegEdit.

Go to Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Bethesda Softworks

If not found Create New Key and name it 'Skyrim Special Edition' for SE.

Right click the 'installed path' location String and change Value data to location of your game's executable. Example: C:\Program Files\Steam\steamapps\common\Skyrim Special Edition

If that doesn't work, try this instead:

Open RegEdit.

Go to Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\

If you can not see 'Steam App 489830' in the list add it.

Inside \Steam App 489830 create a new 'String Value' called InstallLocation

Right click the 'InstallLocation' location String and change Value data to location of your game's executable. Example: C:\Program Files\Steam\steamapps\common\Skyrim Special Edition

- [x] I have browsed through the other issues and confirmed that this issue has not been reported already
- [x] I made sure that I have applied the template for my bug report

**Comment by Mulras** [comment]
Open RegEdit.

Go to Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Bethesda Softworks

If not found Create New Key and name it 'Skyrim Special Edition' for SE.

Right click the 'installed path' location String and change Value data to location of your game's executable. Example: C:\Program Files\Steam\steamapps\common\Skyrim Special Edition

If that doesn't work, try this instead:

Open RegEdit.

Go to Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\

If you can not see 'Steam App 489830' in the list add it.

Inside \Steam App 489830 create a new 'String Value' called InstallLocation

Right click the 'InstallLocation' location String and change Value data to location of your game's executable. Example: C:\Program Files\Steam\steamapps\common\Skyrim Special Edition

**Comment by Dragonisser** [comment]
Duplicate: https://github.com/SkyrimTogether/issues-launcher/issues/8

**Comment by Mulras** [comment]
> Duplicate: [SkyrimTogether/issues-launcher#8](https://github.com/SkyrimTogether/issues-launcher/issues/8)

what do you mean?

**Comment by Dragonisser** [comment]
You posted the fix for the "Game not found" issue. This issue has been reported already and has nothing to do with the game either.
