### ISSUE TITLE
Can't connect local clients with each other

### ISSUE THREAD

**Issue by KickerMix** [SkyrimTogether/issues-game#277]
## Description

I'm trying to create a server, launch 2 copies of Skyrim SE, connect them and play in same server, but after connecting to the server and pressing "Launch Party" it stuck and nothing happens (I was waiting about 15 minutes).

## Steps to reproduce

How to reproduce this issue:

1. Start the 2 copies of the game.
2. Connect them to the server.
3. Press "Launch Party".
4. Nothing happens

## Reproduction rate

100%

## Expected result

Play as other people playing with each other

## Your environment

    The Elder Scrolls V: Skyrim Special Edition
    
     Windows 10 x64

## Evidence (optional)

![image](https://user-images.githubusercontent.com/27219313/57971786-0a8f2580-79ac-11e9-8210-2f4554fb8067.png)

**Comment by WopsS** [comment]
You don't need to click "launch party".

**Comment by KickerMix** [comment]
Yeah, already got it. Sorry for bothering.

**Comment by WopsS** [comment]
No problem.
