### ISSUE TITLE
Cannot save

### ISSUE THREAD

**Issue by Vaaman42** [SkyrimTogether/issues-game#278]
## Description

While playing Skyrim Together, I can't save the game.
Tried to save before connecting to the server, while connected, and after disconnecting.
If I start Skyrim normally through steam, I can save.
My friend (Who has the same environment as me) has the same issue.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Try to save.

## Reproduction rate

Everytime

## Expected result

Being able to save

## Your environment

* Game edition:
    * The Elder Scrolls V: Skyrim
    
 * Operating system:
    * Windows 10 x64

## Final checks for the reporter

- [x] I have browsed through the other issues and confirmed that this issue has not been reported already

- [x] I made sure that I have applied the template for my bug report

**Comment by Louxe** [comment]
Yes I have the same problem with the same game version

**Comment by WopsS** [comment]
A fix should be available in the launcher.

**Comment by loochek** [comment]
Manual saves still don't work, but auto- and quicksaves works fine
