### ISSUE TITLE
Manual save from UI don't work

### ISSUE THREAD

**Issue by loochek** [SkyrimTogether/issues-game#281]
## Description

Wheh I'm trying to save from the UI, nothing happen, only "Saving..." label appears for a moment
At the same time autosaves, quicksaves and "save" console command work fine

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Try to save from the UI
3. Get nothing

## Reproduction rate

Always

## Expected result

Saved game

## Your environment

The Elder Scrolls V: Skyrim non-SE
Windows 10 x64

## Final checks for the reporter

- [x] I have browsed through the other issues and confirmed that this issue has not been reported already
- [x] I made sure that I have applied the template for my bug report

**Comment by Dumbeldor** [comment]
related #291 
it's fixed now.
