### ISSUE TITLE
Game crashes when try to come to the friend

### ISSUE THREAD

**Issue by loochek** [SkyrimTogether/issues-game#282]
## Description

When I come to my friend closely, game crashes

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Go with friend to the same cell
4. Go closer to your friend or TP to him
5. Crash

[5ebe81fc-0f6f-4bdf-9844-b68433e99e2d.zip](https://github.com/SkyrimTogether/issues-game/files/3194993/5ebe81fc-0f6f-4bdf-9844-b68433e99e2d.zip)

## Reproduction rate

We tried to stay in the same place several times
There is a chance to stay together several seconds

## Your environment

The Elder Scrolls V: Skyrim non-SE
Windows 10 x64

## Final checks for the reporter

- [x ] I have browsed through the other issues and confirmed that this issue has not been reported already
- [x] I made sure that I have applied the template for my bug report

**Comment by LazyMoe** [comment]
i have the same problem with Skyrim non-SE and have given up on making it work
i have tried SE as well but my friend can't even connect for some weird reason
Windows 7 x64

**Comment by hadvar101** [comment]
I have the same problem. non-SE, no mods, fresh installed

**Comment by Donnitallo** [comment]
My friend and I had the same problem. After connecting, after 30 seconds or 1 minute, throws out of the game both. After starting the game, the server is no longer connected, it is necessary to restart the server.
Sorry for my bad english)
Version: SE

**Comment by AustinLeath** [comment]
This is 100% reproducible. I can confirm

**Comment by BlackDark67** [comment]
Same Problem :( I know you dont much like Oldrim.. but we are players too.

**Comment by AkiraJkr** [comment]
I can confirm this can be reproduced, even if you just left a house and there was a player outside.

**Comment by AustinLeath** [comment]
I have just checked. This occurs in Special edition as well. 100% reproducible.

**Comment by GR1ML0CK** [comment]
Same issue as well. 2 players. Both running SE. Fresh install. Only mod is "Alternate Start - Live Another Life"

**Comment by Konkachu** [comment]
Same issue, 100% reproducible. Both running Skyrim: NON SE. We tried walking really slowly towards each other and stayed still when we were really close. walked closer a-bit more and it crashed. In multiple locations as well. No Mods, fresh install however characters were loaded from previous saves before mod.

**Comment by LazyMoe** [comment]
still 100% reproducible
even doing it Lan won't work

**Comment by LazyMoe** [comment]
it says remove_npc when my friend join

**Comment by Ri1us** [comment]
I can also confirm that the game crashes and or disconnects when two players enter the same cell

**Comment by gesoteric** [comment]
How has this issue not been resolved? 18 days to resolve an issue? Atleast provide us with an update. Any expected timeframes? Release dates? I have not been able to play with my friend since the beginning (before this issue was raised).

**Comment by loochek** [comment]
This is nightly builds, it's not intended for serious playing

чт, 6 июн. 2019 г., 12:47 gesoteric <notifications@github.com>:

**Comment by f13rce** [comment]
> How has this issue not been resolved? 18 days to resolve an issue? Atleast provide us with an update. Any expected timeframes? Release dates? I have not been able to play with my friend since the beginning (before this issue was raised).

I hope you understand that we're not a company, but volunteers working on this in our spare time? We cannot give estimates because anything else that is more important such as life gets in the way.

We've fixed plenty of bugs and crashes in the meantime but not this one, as shown in #git-dev on our Discord. I know you're willing to play, but right now we're releasing the latest build we can possibly bring during the development, which is not guaranteed to be crash-proof giving the enormous implications we have to work around in Skyrim.

**Comment by gesoteric** [comment]
Here we are... 2 and a half months since this was raised.. Couldn't we just get somebody dedicated to this task? I understand issues are resolved (which aren't this one), but this is a critical issue which does not allow players to do what you claim we can do. Once again, do we have any expected timeframes for when this will be picked up?

**Comment by Neusor** [comment]
We appreciate the support, but it wouldn't be wise to implement features currently.

Right now we're reworking the network library, not everyone in the developers team has the required skills or the time to work on it, and even though it's open source, the same applies here, not everyone has the required skills or time to work on it.

If we would try to fix things right now, it just wouldn't be a wise decision. It would be like building on a broken foundation of a house, issues are gonna arise later.

So just be patient, and if you have the required skills to work on the network library, feel free to head to [the repository on GitHub](https://github.com/tiltedphoques/TiltedNetwork).

**Comment by Makuta-Teridax** [comment]
is there a update concerning this issue? been almost a year and am just curious since i am new to Skyrim Together and am experiencing this issue.

**Comment by AustinLeath** [comment]
I have given up honestly.

**Comment by f13rce** [comment]
Hi there,

> is there a update concerning this issue? been almost a year and am just curious since i am new to Skyrim Together and am experiencing this issue.

We've dropped Oldrim support, as mentioned here: https://old.reddit.com/r/SkyrimTogether/comments/fshjqm/update_31032020/

We're also working on a new codebase, so for now we'll keep these issues in mind but won't directly address them because they don't directly apply to the new codebase.

**Comment by GR1ML0CK** [comment]
@f13rce This issue is not exclusive to oldrim as several have pointed out here. The issue occurs in both se and non se

**Comment by cikeZ00** [comment]
> 
> 
> @f13rce This issue is not exclusive to oldrim as several have pointed out here. The issue occurs in both se and non se

Actually when it comes to SE, its most likely either a corrupt save or a 3rd party app or mod is causing it to crash.
I personally have not experienced any crashes on SE.

**Comment by GR1ML0CK** [comment]
It occurs in a fresh install with no mods, new game on se.
