### ISSUE TITLE
Oldrim Crash/Freeze

### ISSUE THREAD

**Issue by Huebsta** [SkyrimTogether/issues-game#283]
## Description

When i Press Alt+Tab to get to Desktop and then Tab back into the game. The game crashes.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Hit Alt+Tab to get to desktop.
3. Go back into the game.
4. Freeze.

## Reproduction rate

Always

## Expected result

Game freezes. Have to restart.

## Your environment

* Game edition 
    * The Elder Scrolls V: Skyrim
    
    
 * Operating system :

    * Windows 10 x64

## Evidence (optional)

Show us what happen.

## Final checks for the reporter
There is no .dmp file created.

**Comment by loochek** [comment]
This is problem of Skyrim, not ST

**Comment by Pokang** [comment]
As said previously, this is a bug that's been on Oldrim since its release, unrelated to ST.
