### ISSUE TITLE
Me and my friend cannot see each other, and nothing is synced.

### ISSUE THREAD

**Issue by Jack-Rickwood** [SkyrimTogether/issues-game#285]
## Description

Even though both me and my friend are connected to the same server, we cannot see each other, and nothing is synced. We can still see each others messages and it says that we are successfully connected but it even we cannot see each other. We both have the same language game, and the same version game. We are playing over LAN with no internet access.

## Steps to reproduce

How to reproduce this issue:

1. Open <Skyrim Directory>/server/server_r.exe on host pc (as admin).
2. Both launch skyrim from harbor.
3. Both load save past the intro.
4. Connect to 127.0.0.1:10578 on host pc.
5. Connect to <ipv4>:10578 on connecting pc.
6. Go to same spot.

## Dump File

There is no dump file. Here are the log files just in case: 
Log 1: [skyrim_together_2019-05-18.log](https://github.com/SkyrimTogether/issues-game/files/3200209/skyrim_together_2019-05-18.log)
Log 2: [skyrim_together_2019-05-21.log](https://github.com/SkyrimTogether/issues-game/files/3200210/skyrim_together_2019-05-21.log)
CEF Log: [cef_debug.log](https://github.com/SkyrimTogether/issues-game/files/3200211/cef_debug.log)

## Reproduction rate

Every time.

## Expected result

We cannot see or interact with each other, also nothing is synced.

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition
    * Windows 10 x64

## Final checks for the reporter

- I have browsed through the other issues and confirmed that this issue has not been reported already
- I made sure that I have applied the template for my bug report

**Comment by Gryffen1971** [comment]
@Jack-Rickwood , Myself and my friend also have experienced the same problem you and your are having. Ours is with "The Elder Scrolls V:  Skyrim" but, it seems there is same issue with the SE version. As of this moment we do not have logs to submit. We will try again and get our logs together and submit them here also.

**Comment by Neusor** [comment]
That's likely because you're both having set the game in different languages, we're working on a fix for that.

**Comment by Dumbeldor** [comment]
Hi,

We fixed the problem with the lastest version of the nighty :)

**Comment by Gryffen1971** [comment]
@Neusor Both of our games are set for "English". How would a different language effect seeing another character?

**Comment by Dovachiin** [comment]
@Gryffen1971 because cells are loaded by names, so if you are using two different languages, then the same area would have two different names, meaning instead of being in the same cell, you’d be in two different cells. For example if you were playing with someone who had their language as German, they’d be in “Himmelsrand” where as you’d be in “Skyrim”. However I believe this problem has been solved.

**Comment by Gryffen1971** [comment]
@Dovachiin Thank you for the explanation. That does makes alot of sense.
