### ISSUE TITLE
Crash to desktop upon player death

### ISSUE THREAD

**Issue by laserglitch** [SkyrimTogether/issues-game#289]
## Description

>Crash to desktop occurs for anyone else who is in the same cell as another player who dies or is dead, though not the person who dies.

## Steps to reproduce

How to reproduce this issue:

1. Get a buddy to connect or join you in the same cell as you
2. Murder your buddy
3. Crash to desktop immediately

.dmp file: [88c15a86-2322-4992-8e34-c782587f325e.zip](https://github.com/SkyrimTogether/issues-game/files/3210994/88c15a86-2322-4992-8e34-c782587f325e.zip)

## Reproduction rate

100% of the time.

## Expected result

When someone dies everyone sees the other player in a downed state.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 10 x64

## Evidence (Optional)

None to give, sorry.

## Final checks for the reporter

- [ x ] I have browsed through the other issues and confirmed that this issue has not been reported already
- [ x ] I made sure that I have applied the template for my bug report

**Comment by AustinLeath** [comment]
I can confirm, 100% reproducible.

**Comment by Dumbeldor** [comment]
Hi @laserglitch 

Thanks for this report, is that the server side crashing ? I just did severals tests, i've never had a client side crash.

**Comment by Pokang** [comment]
Reviving being very buggy, it has been removed as a whole, and you now load your latest save instead of going into a down animation. Therefore this bug should not exist anymore.
