### ISSUE TITLE
Shout incorrect Rot

### ISSUE THREAD

**Issue by SteamDosh** [SkyrimTogether/issues-game#29]
## Description

Shout rot is incorrect, unable to set either via Actor.rot , seems to always be facing towards the player 

https://clips.twitch.tv/BlushingImpossibleGullKappaPride

## Steps to reproduce

Cast Fus ro dah

## Evidence (optional)

https://clips.twitch.tv/BlushingImpossibleGullKappaPride

**Comment by WopsS** [comment]
I can't reproduce this. The only way to reproduce this is to force set the target to the player, maybe there is a problem in getting the spell target?

**Comment by WopsS** [comment]
When I use [Whirlwind Sprint](http://elderscrolls.wikia.com/wiki/Whirlwind_Sprint) spell target will remain set to the other player.

This is in `CastSpell` function.

![image](https://user-images.githubusercontent.com/3403191/35422741-869efe64-024a-11e8-86c2-3247bee71f94.png)

**Comment by Evayr** [comment]
In my update I tried to guess the spell target - but it seems to fail. I can revert that guesstimation, but then we have no option for targeted spells anymore.

**Comment by Evayr** [comment]
Fixed it in my branch, but now spells with a spell target doesn't work. We need a proper way to determine the spell target of the cast spell.
