### ISSUE TITLE
Game Saves not working in latest build

### ISSUE THREAD

**Issue by Meek97** [SkyrimTogether/issues-game#291]
Saving of any form seems to be broken / disabled in the latest build of Skyrim Together (HEAD@e9810a832)
Manually saving through the menu, quick saving, auto saving, and the save command all do not actually create a new save file.

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Try to save the game yourself, or trigger an auto-save
3. A new save file is not created

[An Example of the Problem](https://gfycat.com/GloriousFreshKittiwake)

no DUMP file, since this issue does not cause a crash

## Your environment
* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 10 x64

## Final checks for the reporter
- [* ] I have browsed through the other issues and confirmed that this issue has not been reported already
- [* ] I made sure that I have applied the template for my bug report

**Comment by Doktozock** [comment]
I have the same problem

**Comment by konoufo** [comment]
Same here

**Comment by M0RG4N01** [comment]
I recently found out that I could save whilst being connected to a server, however when i'm not connected I cannot save. You guys might want to try connecting to the server and trying to save as a workaround for now?

**Comment by Dumbeldor** [comment]
Hi,
Thanks for reports ! I'm reproducing it. I'm trying to watch. 
I'll keep you informed. :)

**Comment by Dumbeldor** [comment]
The problem is fixed, it will be available in the next nighty normally.
Feel free to confirm that you no longer have any problems.

Thanks.

**Comment by M0RG4N01** [comment]
@Dumbeldor Great Job! <3

**Comment by Dumbeldor** [comment]
Thanks ! :*
