### ISSUE TITLE
Cant launch

### ISSUE THREAD

**Issue by TheGameGeek** [SkyrimTogether/issues-game#297]
I was able to launch skyrim together just fine a little bit ago and now whenever i tried to launch it returns this in the debug console
\src\common\processpipe_any.cpp (246) : Assertion Failed: OpenFileMapping returned NULL (errno=2)
\src\common\processpipe_any.cpp (246) : Assertion Failed: OpenFileMapping returned NULL (errno=2)
Then it closes the console (yes it says it twice)

**Comment by Pokang** [comment]
Please reopen this issue using the template we provided for it.
