### ISSUE TITLE
Saved game while down caused character to die and respawn glitched

### ISSUE THREAD

**Issue by Gornjolf** [SkyrimTogether/issues-game#299]
## Description

I died from jumping off a tower, so I was lying there, and no one could help me, so I figured I'd save the game and quit. However, when I saved, my character died, and a save loaded. However, I had my sword out, and I could move around, but there was no walking animation, I just drifted around. But I could move around and talk to people still. THis continued until it forced me to "respawn" in the temple.
## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Get character killed.
4. Save the game.

## Reproduction rate

I was able to reproduce it, although I only tried once after it happened.

## Expected result

The character doesn't die if the game is saved. 
## Your environment

    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):

    * Windows 10 x64

## Final checks for the reporter

- [ x] I have browsed through the other issues and confirmed that this issue has not been reported already
- [x ] I made sure that I have applied the template for my bug report

**Comment by M0RG4N01** [comment]
If you get killed that means the character has died, if you are in multiplayer with a friend then he/she can revive you. However, if you are alone then you should just /respawn then go back to where you were using fast travel. 

I'm not sure how you expected your character not to die by saving if you got killed, saving the game whilst being killed would make an issue like that but I wonder if they could add a check for if you were killed and put you back into the down status again once you have loaded the save which would fix the issue of walking around with no walking animation or something similar that would help fix that issue.

**Comment by Dumbeldor** [comment]
Hi,
Thanks for your report !
You can block the save when the player is dead otherwise :P Izi fix.

**Comment by Dumbeldor** [comment]
It seems from @M0RG4N01  that the bug can be recreated if you load a part when you are dead.
And more seriously, I'd try to reproduce the problem and think about a fix.

**Comment by Pokang** [comment]
This is an issue with fall damage deaths that we've been aware of for a while, it will probably need a rework of the death system.
In the meantime, typing "resurrect" twice or thrice after having clicked your character should reset your state and your animations.

**Comment by Pokang** [comment]
Reviving being very buggy, it has been removed as a whole, and you now load your latest save instead of going into a down animation. Therefore this bug does not exist anymore.
