### ISSUE TITLE
Healing Hands and Heal Other

### ISSUE THREAD

**Issue by Enieu** [SkyrimTogether/issues-game#3]
## Description

Healing Hands and Heal Other can't cure other players.

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition

* Mods used: None

## Reproduction rate

Everytime

## Steps to reproduce

Using the Healing Hands and Heal Other spell on player.

## Actual result

No health regeneration and no visual effects of the spell happen on players (on the player who is on the receiving end).

## Expected result

Healing visual effect and life regeneration should occur.

## Note
AOE spell Grand Healing does work.

**Comment by Evayr** [comment]
I think this has to do with us being unable to mark a spell target, since OnMagicEvent Handler doesn't provide a target. However, we could add in a GetCombatActor_Native check, though I wouldn't know how reliable that is.

**Comment by Evayr** [comment]
[OnMagicEffectApply](https://www.creationkit.com/index.php?title=OnMagicEffectApply_-_ObjectReference) Handler seems to catch the event, but only has a [MagicEffect](https://www.creationkit.com/index.php?title=MagicEffect_Script_(Papyrus)) to work with. It is unsure how to apply this effect onto others freely.

**Comment by Evayr** [comment]
Probably fixed: https://github.com/Evayr/SkyrimOnline-private/commit/71534ac089b32c130d52e5a5dfc748431819e93b

Re-open if the issue still occurs
