### ISSUE TITLE
There should be an option to automatically reconnect upon connection error or unexpected disconnect. Also should remember last entered ip.

### ISSUE THREAD

**Issue by ThiCrusader** [SkyrimTogether/issues-game#300]
There should be an option to automatically reconnect upon connection error or unexpected disconnect. Also should remember last entered ip.

**Comment by Kiaos** [comment]
I agree this is a highly requested feature!

**Comment by Dumbeldor** [comment]
Hi,

Great idea.

Thanks.

**Comment by Dumbeldor** [comment]
Hi @ThiCrusader !

I did it today : https://www.youtube.com/watch?v=Z81jPbGurh0&feature=youtu.be ;)
Thanks for your idea ! If you have a comment about what I've developed, don't hesitate.

Have fun
