### ISSUE TITLE
Can't see dropped items & join party not working

### ISSUE THREAD

**Issue by JacobDeMolay** [SkyrimTogether/issues-game#307]
## Description

After I connect to my friend's server we got different loot in chests and containers and we can't see items dropped by other on the floor.  We also are on the same server but option to join party(or create) does not work, it seems to be loading and loading and loading but after 'round 10 minutes nothing happens

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Can't see same items or join party

Happens every time

* Game edition (choose on which edition do you have problems):

    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):

    * Windows 10 x64

**Comment by M0RG4N01** [comment]
Currently, chests, loot dropped, etc are not synced. However, you can try use a mannequin to trade as people have been successfully with that.
