### ISSUE TITLE
Duplication of NonUnique NPCs in cells

### ISSUE THREAD

**Issue by bvanseg** [SkyrimTogether/issues-game#309]
## Description

Upon entering a cell (with multiple players inside the cell), NPCs without special names within the cell have a chance to duplicate for certain players (mostly non-hosts).

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Go to Whiterun. The host should go there as well.
4. Examine the guard NPCs. Some of them will be duplicated (confirmed for clients, unconfirmed for hosts).
5. If there is no duplication occurring, the host may need to enter the cell first and *then* have the client enter the cell.

## Reproduction rate

About 75% of the time during testing.

## Expected result

The expected result will be duplicate guards. **It should be noted that duplication ONLY occurred with nonunique NPCs and NOT with named NPCs like Adrianne, Belethor, etc.**

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 10 x64

## Other Notes

The method by which this bug was discovered in detail was:
1. The client was in Dragonsreach completing the Bleak Falls Barrow quest.
2. The host entered and remained in Whiterun while the client was in Dragonsreach completing the quest. (They entered through the doors, not through death teleporting)
3. The client then left Dragonsreach to continue the Dragon Rising quest. The duplication was discovered then.

About the duplicate NPCs:
1. These duplicate NPCs were always NonUnique NPCs. In the case of Whiterun, the Whiterun Guards.
2. If the original NPC was attacked, the duplicates would remain in place.
3. The duplicates otherwise would remain in place and talk all the same.

Conclusion:
This is likely just a client-end duplication of the non unique actors. The duplicates function client-side when interacted with by the client, but don't seem to have a controller entity that moves them server-side.

**It's also worth noting that the duplicates remain in the game even after disconnecting from the server. Hell, even launching Skyrim SE without Skyrim Together, the duplicates remained.**

## Final checks for the reporter

- [X ] I have browsed through the other issues and confirmed that this issue has not been reported already
- [X ] I made sure that I have applied the template for my bug report

**Comment by M0RG4N01** [comment]
I believe this bug was highlighted as known in the discord announcements, etc. They currently do not have an estimate for when a fix will be released and they have said to not expect any major changes with development at this time considering that we are now into the period of exams. The information you have provided in your notes may provide useful though, and I have personally experienced this issue too. 👍

**Comment by javsanpar** [comment]
Be sure you are using docker image `tiltedphoques/st-game-server` and not `titledphoques/st-game-server`

**Comment by bvanseg** [comment]
It looks like Yamashi has already merged the guard-dupe-fix branch into master, and it's already been built. I'm going to assume that they fixed this. Closing.
