### ISSUE TITLE
Trim IP string in server field.

### ISSUE THREAD

**Issue by kamaii** [SkyrimTogether/issues-game#314]
## Description
Any leading or trailing white space in the IP field will prevent connecting.
Could cause less tech savvy users to be confused as to why they can't connect.

Related formIDs|
---------------|

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Enter IP with trailing or leading space.
3. Unable to connect.

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**.

## Reproduction rate

100%

## Expected result

Connect as usual.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)

![20190619163755_1](https://user-images.githubusercontent.com/16251746/59808378-db244f00-92b0-11e9-8d72-8983c68da6af.jpg)

## Final checks for the reporter

- [x] I have browsed through the other issues and confirmed that this issue has not been reported already
- [x] I made sure that I have applied the template for my bug report

**Comment by Dumbeldor** [comment]
Hi @kamaii !
Thanks for your bug report, i just corrected that !
It will be present in the next nightly build ;)
Have fun !
