### ISSUE TITLE
Joining a server with another new player at helgen causes dialogue to halt.

### ISSUE THREAD

**Issue by rzjnzk** [SkyrimTogether/issues-game#323]
Whilst in the carriage to Helgen at the beginning of the game, the mod prevents the player from joining a server, though immediately after customizing their character the user can join a server. Both a friend myself did this and experienced the dialog halting, as well as an NPC blocking my path to the block. In retrospect, this may have resolved itself in time, though perhaps the period in which a player can not join a server should be extended until the player is unbound, and free to move as they please.

I am running Skyrim Legendary Edition with bugfix and texture mods, as was my friend.

**Comment by Pokang** [comment]
We've been very clear with the fact that you should not try to connect until out of Helgen, you probably missed that bit of info... Because it will indeed cause issues like this.
