### ISSUE TITLE
Crash Upon connecting to my own server

### ISSUE THREAD

**Issue by naxrampvp** [SkyrimTogether/issues-game#329]
## Description; start up skyrim lastest save than Rctrl connect enter 127.0.0.1:1578 im in for a moment and than crash to desktop

Crash upon entry
Bug report=
{"date":"2019-08-12 05:29:44,005", "level":"INFO", "event":"server_state", "value":"started", "token":"" }
{"date":"2019-08-12 05:32:08,943", "level":"INFO", "event":"connected", "connection_id":2014507436 }
{"date":"2019-08-12 05:32:09,008", "level":"INFO", "event":"hello_received", "client_protocol":3574881509, "server_protocol":3574881509 }
{"date":"2019-08-12 05:32:09,630", "level":"INFO", "event":"hello", "connection_id":2014507436, "name":"Dorian" }
{"date":"2019-08-12 05:32:21,463", "level":"ERROR", "event":"player_dtor_find_new_cell_host", "error":"npc_is_null" }
{"date":"2019-08-12 05:32:21,463", "level":"INFO", "event":"disconnected", "connection_id":2014507436 }

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to my own server.
3. Crash.

## Reproduction rate

How many times can you reproduce it?
100%
## Expected result

Describe your expected result.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
  
    * Windows 7 x64

## Evidence (optional)

Show us what happen.

**Comment by Neusor** [comment]
Sounds like an corrupt save, best way to prevent this right now, is to disconnect and then save. Unfortunately corrupt saves can still happen, even when you disconnect and then save.

**Comment by naxrampvp** [comment]
How come the server doesn't come on like normal? Ive seen videos where it is meant to say the Port:1578 but it only says {"date":"2019-08-12 05:29:44,005", "level":"INFO", "event":"server_state", "value":"started", "token":"" } which doesn't make sense could my server.exe be messed up?

**Comment by Neusor** [comment]
@naxrampvp 
> How come the server doesn't come on like normal? Ive seen videos where it is meant to say the Port:1578 but it only says {"date":"2019-08-12 05:29:44,005", "level":"INFO", "event":"server_state", "value":"started", "token":"" } which doesn't make sense could my server.exe be messed up?

That's normal behavior since the network library update. If you're unable to connect try the firewall fix in [this guide](https://docs.google.com/document/d/1zQKsZSSwDIe9zOuYRux0_BKXr6ojzXpYFsiYSk-ygxg).

**Comment by NikUk5** [comment]
same problem, right?

**Comment by NikUk5** [comment]
The problem is not saving, deleted passed, can not join .... (crash)

**Comment by zxyxz** [comment]
I encountered the same problem, I solved it by upgrading to the latest version!

**Comment by Pokang** [comment]
> The problem is not saving, deleted passed, can not join .... (crash)

Could you provide us a screenshot of your game installation folder please?
