### ISSUE TITLE
[UI][feature request] connect to password/token protected server

### ISSUE THREAD

**Issue by MasterMNB** [SkyrimTogether/issues-game#333]
At the moment if i try connect to a token protected server without a password, i get only a disconnect message.   
![image](https://user-images.githubusercontent.com/3178390/64718928-76e7e480-d4c7-11e9-872e-94345a794c6b.png)

At the direct connect function would an error message that say's please provide a token good.  
And it would be better for the public list, if it would ask for the token and indicates that the server is password protected in the list.

![image](https://user-images.githubusercontent.com/3178390/64719073-caf2c900-d4c7-11e9-8e08-3fbff2d8c17d.png)

**Thanks for all the effort**

**Comment by yamashi** [comment]
Fixed, we simply don't allow password protected servers to be listed publicly anymore.
