### ISSUE TITLE
Teleporting Dragons

### ISSUE THREAD

**Issue by Leiharl** [SkyrimTogether/issues-game#336]
## Description

Dragons, while on the air, keep teleporting instead of flying, glitching around the sky, making them very dificult to hit, and therefore, to land and fight.

## Steps to reproduce

How to reproduce this issue:

1. Host and non-host player have same issue.
2. Being connected to server.
3. Start a dragon fight.

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in [**<Skyrim_Directory>/Data/Online**.]: Attached.
[DMP File.zip](https://github.com/SkyrimTogether/issues-game/files/3610822/DMP.File.zip)

## Reproduction rate

Every dragon we fight.

## Expected result

Fixed teleporting dragons glitch.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition
    
 * Operating system (choose one):
    * Windows 7 x64

## Final checks for the reporter

- [x] I have browsed through the other issues and confirmed that this issue has not been reported already
- [x] I made sure that I have applied the template for my bug report

**Comment by Pokang** [comment]
Dragons have a very special way of animation and we haven't synced them yet, they should be synced normally when they hit the ground though.
