### ISSUE TITLE
Cannot properly finish character creation

### ISSUE THREAD

**Issue by Evayr** [SkyrimTogether/issues-game#34]
## Description

The no-freezing utility causes character creation to be broken. In Alternate Start mod, the camera doesn't rotate towards the player. On vanilla, the game pretends you're already done creating your character (scripts continue to run) while the character customization options are still on the screen.

## Your environment

    * The Elder Scrolls V: Skyrim
    * The Elder Scrolls V: Skyrim Special Edition

* Mods used: Both Alternate Start and none

## Reproduction rate

Always

## Steps to reproduce

1: Load Skyrim with our mod
2: Start a new savegame
3: See character creation go broken

## Solution suggestion

Disable the no-pause feature while not connected?

**Comment by AlexH-16** [comment]
I swear no-pause was only running on server connect...
Is this caused by pause?

**Comment by Evayr** [comment]
I am pretty sure it is, as my game doesn't pause when I open a menu with the mod loaded. It could that it's only in my branch - but I updated to WopsS/rework9000's latest before testing it.

**Comment by AlexH-16** [comment]
Np. Easy fix, do we want just to disable no-pause completely while offline? Or find a work to fix character creation with no-pause on?

**Comment by AlexH-16** [comment]
Done.
