### ISSUE TITLE
[BUG] Customized & Enchanted Gear lose atributes and name

### ISSUE THREAD

**Issue by BiervampirAUT** [SkyrimTogether/issues-game#342]
Hi

When I put my echanted gear with custom name in a static objective to give it to a friend, the gear will lose all atributes and its name.
Thanks for the mod <3

best regards,
Klaus

**Comment by Samatuer** [comment]
Same here

**Comment by Dragonisser** [comment]
1. You deleted the whole template.
2. Custom enchanted or forged items arent synced yet and wont come anytime soon.

**Comment by Samatuer** [comment]
kay' thanks for your time <3
