### ISSUE TITLE
Weapon section disappear when a player joins the local server

### ISSUE THREAD

**Issue by Mass1milian0** [SkyrimTogether/issues-game#343]
we tried both modded and vanilla, the result is the same, basically the weapon section disappears once a player join the server (if you are alone in the server it works) alos if you join the local server and a player is already there the result is the same, hoewer public servers do work,, in the video from this link: http://www.filedropper.com/bug

you can see what is happening in there

P.S. We are using hamachi to establish a "lan" connection

**Comment by Dragonisser** [comment]
1. Use the template
2. Upload to youtube, not gonna click that shady link and download some random video file

**Comment by Mass1milian0** [comment]
> 1. Use the template
> 2. Upload to youtube, not gonna click that shady link and download some random video file
> 
> And im pretty sure your vanilla skyrim wasnt clean at all.

first of all, i can assure you that my vanilla skyrim was clean

now, i'm sorry for not using the template, i'll use it in this message, also i uploaded the video on youtube

#### Issue description

weapon category disappearing in local servers with more than one persons with or without mods

#### Steps to reproduce the issue

1.  enter a local server in which there is already somebody connected
2.  open the inventory

#### What's the expected result?

the weapon category should have appeared once i opened the inventory

#### What's the actual result?

no weapon category

#### Additional details / screenshot
https://youtu.be/mr5zhx727vg

**Comment by Pokang** [comment]
We cannot reproduce this issue, both with and without SkyUI, and it's the first time I hear of it to be honest. If you find steps that make it reproduceable with Vanilla skyrim on multiple machines, then please reopen the issue with more infos, thanks!
