### ISSUE TITLE
Inability to Sleep.

### ISSUE THREAD

**Issue by Paw-w** [SkyrimTogether/issues-game#35]
## Description

Not possible to sleep in beds, probably related to the wait removal. The inability to sleep causes issues when attempting to start/continue the Dark Brotherhood questline. Also means you can not work for Miraak at his temple every sleep in Dragonborn DLC

## Your environment
    * The Elder Scrolls V: Skyrim Special Edition

* Mods used:
https://i.imgur.com/3pRKW4G.png
Along with a Shield pack with some custom shields and a mod which changes loadscreen item/info to Skyrim Together logo and info.

## Reproduction rate

How many times can you reproduce it?
Endlessly.

## Steps to reproduce

1. Find sleepable bed/bed-like object.
2. Try to sleep.

## Actual result

Describe your actual result.
Can't sleep, nothing happens when sleep button is pressed.

## Expected result

Describe your expected result.
Sleep sequence starts.

## Evidence (optional)

Show us what happen.
None.

**Comment by AlexH-16** [comment]
This is related to some menus becoming 'inoperable' with no-pause on.

**Comment by Evayr** [comment]
Same goes for waiting when attempting to hit the Sleep key (T by default)

**Comment by AlexH-16** [comment]
I don't think so, functionally it works fine. It's smaller things that are giving issues. Which we can completely build around if need be anyway.

**Comment by WopsS** [comment]
The thing is that this issue is related to saving too. If the pause is disabled some of us can't save. Maybe because you close `LoadWaitSpinner`?

**Comment by WopsS** [comment]
Somewhere is saving code it waits for a ownership for a critical section which is never released by something.

**Comment by Pokang** [comment]
I'm pretty sure you can sleep normally now, I'm not able to try the DB questline right now but feel free to reopen if it still causes issues with sleeping-related questflags.
