### ISSUE TITLE
I can't start Skyrim Together

### ISSUE THREAD

**Issue by ViniciusRFaria** [SkyrimTogether/issues-game#358]
## Description

Oi pessoal, sou Brasileiro me desculpem pelo idioma, mas estou tentando jogar o Skyrim Together mas aparece uma mensagem dizendo: O sistema não pode encontrar o arquivo especificado. An error ocurred when trying to read "pid" from "HKEY_CURRENT_USER\\SOFTWARE\\Valve\\Steam\\ActiveProcess"

Eu instalei tudo certo, eu acho, indiquei a pasta do jogo e ele atualizou. Mas quando clico em jogar ele da a mensagem.
Meu Skyrim é o Legendary Edition e crackeado, pirata.

Related formIDs|
---------------|
[Flames - 12FCD](http://en.uesp.net/wiki/Skyrim:Flames)|
[Nazeem - 1A6A4](http://en.uesp.net/wiki/Skyrim:Nazeem)|

## Steps to reproduce

Eu só tento iniciar o jogo e da a mensagem.

1. Start the game.

**Note**: Please attach the latest dump (**.dmp**) file, you can find it in **<Skyrim_Directory>/Data/Online**. If you believe this bug is related to a specific mod, try disabling that mod and reproducing the bug *before* reporting it - this is valuable information!

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [ X] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Describe your expected result i.e. answer the question "What did you expect would happen?"
Espera que o "Skyrim Together" abrisse e pudesse jogar online

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim
   
    
 * Operating system (choose one):
   
    * Windows 10 x64

## Evidence (optional)

Show us what happened.

![erro](https://user-images.githubusercontent.com/59238280/71452146-2fc0ef00-2758-11ea-8ff5-3dd54d3e386c.PNG)
![erro2](https://user-images.githubusercontent.com/59238280/71452147-2fc0ef00-2758-11ea-81cd-1db23a82da37.PNG)

**Comment by Ueine** [comment]
We don't support pirated copies of the game.

**Comment by ViniciusRFaria** [comment]
I managed to make the game work, I just needed to download Steam, but on entering a public server, it closes the game. Could it be because I am in Brazil and I enter servers from other countries? Or because the connection itself with public servers is very unstable?

**Comment by Bojanglesworth** [comment]
We do not support piracy. This isn't an issue.
