### ISSUE TITLE
remoteNPC cell change

### ISSUE THREAD

**Issue by SteamDosh** [SkyrimTogether/issues-game#37]
## Description

Remote NPCS refuse to change cell and will stay at a door/entrance

## Reproduction rate

100%

## Steps to reproduce

Have a remote npc attempt to change cell (exterior into interior)

## Expected result

Npc changes cell 👍

**Comment by WopsS** [comment]
Do they have collision?

**Comment by SteamDosh** [comment]
I believe the npc gets stuck in limbo (not delted or disabled) due to our current implementation of cell!=hostCell (hence why they just stand there) 

This is without cell->AddReference currently, needs some work to figure out of that's the correct thing to do and if we need to figure out alternative paths.

**Comment by WopsS** [comment]
Can you check if they have collision?

I RE that `cell->AddReference` from Skyrim, so it should work.

**Comment by Evayr** [comment]
Resolved: https://github.com/yamashi/SkyrimOnline/pull/222
