### ISSUE TITLE
Misplaced, Incorrectly Orientated and floaty NPCs

### ISSUE THREAD

**Issue by Gamepaw** [SkyrimTogether/issues-game#4]
## Description

A short description about your issue or detailed description for a feature request.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

* Mods used: https://i.imgur.com/bcb5nWR.png

## Reproduction rate

How many times can you reproduce it? - Occurs randomly, but can occur multiple times at once.

## Steps to reproduce

Tell us how to reproduce this issue. Walk around and look at the NPCs

## Actual result

Describe your actual result. - Floaty/Misplaced NPCs.

## Expected result

Describe your expected result. NPCs in correct area.

## Evidence (optional)

https://i.imgur.com/LdsxTKU.jpg
https://i.imgur.com/p2U4ESM.jpg
https://i.imgur.com/NtxeqZU.jpg

**Comment by Evayr** [comment]
Looks like something with the initial animation. Not sure why yet but I'll have a look

**Comment by Evayr** [comment]
Fixed: https://github.com/WopsS/SkyrimOnline/pull/62
