### ISSUE TITLE
Lightning Storm (Dual Casting Spell) not ending for non-casters.

### ISSUE THREAD

**Issue by Gamepaw** [SkyrimTogether/issues-game#41]
## Description

When casting Lightning storm, the spell may not end for other players in the game. The spell will also hit everything the caster faces due to the placement.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

* Mods used:

## Reproduction rate

How many times can you reproduce it?
Can be reproduced fairly consistently.

## Steps to reproduce

Cast lightning Storm (0007E8E5) with another player present, the other player will continue seeing lightning storm after the caster has stopped casting it. (Lightning Storm is a high-cost spell, tgm may be needed to cast it for more than 1 or 2 seconds.)

## Actual result

Lightning Storm continues casting for non-caster players.

## Expected result

Lightning Storm should stop.

## Evidence (optional)

https://i.imgur.com/cdVUmOK.gifv and https://clips.twitch.tv/FrozenTolerantDolphinMau5

**Comment by SteamDosh** [comment]
Is this still relevant?

**Comment by Gamepaw** [comment]
Yes

**Comment by SteamDosh** [comment]
Will look into over the next few days, my initial thoughts are we aren't catching the correct 2H interrupt animation and shouldn't be that hard of a fix (i hope, pls god skyrim be nice for once)

**Comment by SteamDosh** [comment]
fixed in upcoming PR (potentially Wopss/101)
