### ISSUE TITLE
'Dying' as werewolf or vampire lord and respawning, respawns you as transformed.

### ISSUE THREAD

**Issue by Gamepaw** [SkyrimTogether/issues-game#43]
## Description

If a player dies while in a werewolf or Vampire Lord form, they will respawn at the Whiterun Temple as the respective creature and will then be attacked by the NPCs

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition 

* Mods used:
Yes

## Reproduction rate

How many times can you reproduce it? Endlessly

## Steps to reproduce

Tell us how to reproduce this issue.

Transform into werewolf or Vampire Lord, 'die' and /respawn or wait to respawn at temple.

## Actual result

Respawns as respective transformations

## Expected result

Respawns as normal character (non-transformed)

## Evidence (optional)

Show us what happen.

Not really proof, but shows aftermath of what happened as a werwolf while in the temple.
https://cdn.discordapp.com/attachments/428521704374140929/438665614131724290/489830_20180425123729_1.png

**Comment by Evayr** [comment]
I'm not sure whether to label this as a bug or as a suggestion. To lose aggro, StopCombatAlarm() could also be called.

**Comment by SteamDosh** [comment]
Need to check for the characters race/buffs for werewolf (Idk how currently), but on death should call StopCombat()

**Comment by SteamDosh** [comment]
Vampire lord is fixed however I am not fixing werewolf transformation being stuck (It is also automatically removed after 2:30min)

Make a new issue for werewolf form however it will probably be archived. Some minor documentation is found at Wopss PR100
