### ISSUE TITLE
Can not navigate Trader NPC inventory/UI

### ISSUE THREAD

**Issue by Paw-w** [SkyrimTogether/issues-game#53]
## Description

Attempt to purchase/trade items with a Trader NPC and attempt to navigate the menu. Instead of scrolling through the list, it will instead do nothing and you will keep getting the generic 'open menu' dialogue from the NPC. 

(Tested on Meat Trader in Whiterun.)
## Steps to reproduce
1. Walk up to trader.
2. Initiate dialogue.
3. Attempt to navigate wares.

## Reproduction rate

Repetitively.

## Expected result

Would have been able to buy or sell items to the trader with no issue.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

Show us what happen.

**Comment by Ueine** [comment]
This is a old bug, you can trade if you press tab again after entering the trade window.

**Comment by SteamDosh** [comment]
@Ueine Potentially related to no-pause?

**Comment by Ueine** [comment]
@SteamDosh I believe it its.

**Comment by CodeineZA** [comment]
@Gamepaw I open up the trade and wait fot the NPC to finish it's dialog.
Click on the NPC once and wait for the dialog to finish.
Press Esc and then go ahead and open up the inventory.

**Comment by Thermalpulse** [comment]
The Dialogue Box sticks after entering the trade menu due to no pause, press ESC to exit the dialogue and you will be able to control the barter menu once again. This is a "bug" with the original Skyrim that isn't possible to see without a mod that unpauses pausing menus. Cheers.

**Comment by Pokang** [comment]
This is not an issue anymore since the no-pause code deletion.
