### ISSUE TITLE
View zooming with middle mouse scrolling within Skyrim UI.

### ISSUE THREAD

**Issue by Paw-w** [SkyrimTogether/issues-game#56]
## Description

Attempting to middle mouse scroll while within the player's inventory window may result in scrolling/zooming between 1st and 3rd person views.

EDIT: This also happens with the actual pause menu.

## Steps to reproduce

1. Open UI.
2. Attempt to scroll with mouse wheel.

## Reproduction rate

Frequently.

## Expected result

Normal navigation would occur, without issues with 1st-3rd person views.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

Show us what happen.

**Comment by Pokang** [comment]
This is not an issue anymore since the no-pause code deletion.
