### ISSUE TITLE
Search button text is really small on Higher Resolutions

### ISSUE THREAD

**Issue by Paw-w** [SkyrimTogether/issues-game#68]
## Description

On a 4K display (3840x2160) the search button text is really small when compared to the rest of the interface.

## Steps to reproduce

1. Open Skyrim Together in 4K (3840x2160)
2. Navigate to Search button.

## Reproduction rate

Always.

## Expected result

Search text would be of similar size to the rest of the text.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

Show us what happen.

**Comment by Pokang** [comment]
That has been fixed, all buttons should now be responsive no matter the resolution.
