### ISSUE TITLE
NPC Heading direction

### ISSUE THREAD

**Issue by SteamDosh** [SkyrimTogether/issues-game#7]
## Description

NPC Heading direction isn't sync'd nor found

## Your environment
    * The Elder Scrolls V: Skyrim
    * The Elder Scrolls V: Skyrim Special Edition

## Reproduction rate
100%

## Steps to reproduce

Move in a direction which isn't forward

## Actual result

NPC freaks out

## Expected result

NPC should be facing the proper direction

**Comment by Evayr** [comment]
Editing the animation graph variables didn't seem to work, though getting them from the player seemed to be the way to go. I'm assuming we need some native call to set the direction.

**Comment by Evayr** [comment]
Fixed the freaking out, but there's still no support for walking backwards and sideways.
