### ISSUE TITLE
NPCs die when disabled and enabled using the console by a non-host

### ISSUE THREAD

**Issue by Thesa22** [SkyrimTogether/issues-game#75]
## Description

If a non-host selects an NPC, and disables and enables them, the NPC Dies on re-enable. They cannot use resurrect either.

## Steps to reproduce

How to reproduce this issue:

1. Open the console
2. Select an NPC
3. Type disable
4. Type Enable

## Reproduction rate

Every time

## Expected result

The NPC re-appears in the game, alive.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

**Comment by SteamDosh** [comment]
This is intended and won't be fixed
