### ISSUE TITLE
 ST launcher will start the normal Skyrim if you haven't started steam beforehand 

### ISSUE THREAD

**Issue by Ueine** [SkyrimTogether/issues-game#82]
## Description

When you launch ST without steam loaded you will have to wait to the steam login phase and after that it will start the normal version of the game instead of ST.

## Steps to reproduce

How to reproduce this issue:

1. Start the game with steam off.

## Reproduction rate

It happens 100% of the time every time.

## Expected result

Should Load ST.

## Your environment

    * The Elder Scrolls V: Skyrim
    * The Elder Scrolls V: Skyrim Special Edition

**Comment by Pokang** [comment]
That has been fixed a while ago with a loader rework.
