### ISSUE TITLE
Werewolf - Chance of crash on attack

### ISSUE THREAD

**Issue by Gamepaw** [SkyrimTogether/issues-game#83]
## Description

Attacking (Slash) while in werewolf may cause a crash for the players who are not the attacking party.
Player 1 - Group Host/Werewolf
Player 2 - Cell Host
Player 3 - Other Player

Related to
#60 and #61 ?

## Steps to reproduce

1. Turn into werewolf
2. Attack other player.

## Reproduction rate

Frequently

## Expected result

No Crash.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim
    * The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

Show us what happen.

**Comment by f13rce** [comment]
Likely to be fixed here: https://gitlab.com/f13rce/Game/commit/6b52bfd6c14ef273d521a1dd51ce31006f8c99c3

Turned out to be a nullptr not being checked beforehand.

Reopen this issue if it still occurs.
