### ISSUE TITLE
UI - Chat will randomly stop receiving or showing messages.

### ISSUE THREAD

**Issue by Gamepaw** [SkyrimTogether/issues-game#88]
## Description

Occasionally, when using the in-game chatbox it will stop showing messages that the player or other players have sent, however others can still see this. For an example P1 - Player with Bug, P2 - Innocent Bystander
P1 Types "Some Words" However they do not see this.
P2 sees P1's "Some Words" in chat.
P2 replies with "Some Other words." in chat, P1 does not see this.

This issue will occasionally fix itself, but disconnecting and reconnecting fixes it straight away. In the case of just waiting, the chat will suddenly post every message that was sent by all the players in quick succession.

This does not seem to apply to local system messages, such as those sent by chat commands.

## Steps to reproduce

How to reproduce this issue:

1. Use the chat

## Reproduction rate

Can not reproduce, happens randomly with seemingly no 'triggers'

## Expected result

Being able to see all the chat messages.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

Show us what happen.

**Comment by WopsS** [comment]
I think this might be because you don't run it on **NgZone**?

**Comment by Gamepaw** [comment]
Something to add, not sure if it was the case for the original report, but when testing a different time. The bug reoccurred for both players, chat wasn't progressing but you would still get the little message popups when the chat was closed.

**Comment by skreborn** [comment]
> chat wasn't progressing but you would still get the little message popups when the chat was closed

So the messages do successfully arrive at the client. Definitely sounds like a change detection issue, probably because of `NgZone` indeed.

**Comment by skreborn** [comment]
The bad news is that both those components use `ClientService.messageReception` as their source, which is run through the correct zone. It's a really weird and highly unlikely situation that those two would fall out of sync.

**Comment by Dumbeldor** [comment]
Fixed

**Comment by Dumbeldor** [comment]
@Gamepaw Can you confirm my fix ? :wut:

**Comment by Dumbeldor** [comment]
You'll have to test it when yamashi has updated the ui in production

**Comment by Dumbeldor** [comment]
Problem solved with #349
