### ISSUE TITLE
Favourites/Q Menu - Unable to change/add numbers.

### ISSUE THREAD

**Issue by Gamepaw** [SkyrimTogether/issues-game#9]
## Description
While using ST, it is not possible to assign numbers to items placed into the favourites menu, or change them.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

* Mods used:
https://i.imgur.com/bcb5nWR.png
## Reproduction rate

Can be reproduced during every instance of ST.

## Steps to reproduce

1. Load save.
2. Favourite an item(s) within your inventory/spells
3. Open Favourite menu. (Q)
4. Attempt to assign/change hotkey of item. (1-8)

## Actual result
Hotkey assignment does not get added or changed. 
If an item is assigned the number you attempt to assign to another, it will instead equip that item instead of changing to the new item.

## Expected result
Hotkeys to be assigned/reassigned to items within the favourite menu without the old items being equipped instead.

**Comment by Evayr** [comment]
This may be fixed with skreborn's new input system. Will wait with investigation before the new UI is in.

**Comment by WopsS** [comment]
That shouldn't matter, we don't enable the UI. Maybe it is because we disabled the pause.

**Comment by WopsS** [comment]
I just tested, it is because we disable the pause.

**Comment by AlexH-16** [comment]
I think I have a good idea how to fix. Don't you worry your silly little Christmas hats.

**Comment by Jostreator** [comment]
it is infact of the pause. happened to me when using a no-pause mod on skyrim LE.
