### ISSUE TITLE
Games crashes when launching via Mod Organizer 2

### ISSUE THREAD

**Issue by jagoxo** [SkyrimTogether/issues-game#91]
## Description

Game won't launch via Mod Organizer 2. 

Related formIDs|
---------------|

## Steps to reproduce

How to reproduce this issue:

1. Start Harbor via Mod Organizer 2 ( with no mods enabled )
2. Press Launch in Harbor
3. Crash.

## Reproduction rate

I got the game to start once of maybe 10-15 tries, so pretty much every time.

## Expected result

Game menu shall appear with Skyrim Together Logo

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

Attaching dump : 
[20190125-164405-6820-7052.zip](https://github.com/SkyrimTogether/issues-game/files/2796854/20190125-164405-6820-7052.zip)

**Comment by Thesa22** [comment]
Did you add to MO2 with the correct Binary and Start In fields filled, according to the guide? 

**How to add/Launch Skyrim together to Mod Organizer 2**
1. On the 'Run Executables' button (next to the Run button), click <Edit>
2. In the window that pops up, add the following fields:
	Title: Skyrim Together
	Binary: [harbor install folder]\Harbor.exe
	Start in: [harbor install folder]
	Check 'Use Application's Icon for shortcuts' (optional)
3. Click Add and Close
4. To launch, Click on Skyrim Together on the 'Run Executables' Button in MO2

**Comment by jagoxo** [comment]
Yes exactly like that. ( with start in Harbor folder ) Sorry that I forgot to write this. Worth adding also is that Im using re-shade enb and have skse installed in my skyrim folder.

**Comment by jagoxo** [comment]
Managed to get the game running after pressing launch a couple of times. Great fun! Been playing for an hour now.
