### ISSUE TITLE
Opening the Steamoverlay pauses the game

### ISSUE THREAD

**Issue by Dragonisser** [SkyrimTogether/issues-game#95]
## Description

^Title. Also seems to desync everything

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Open Steamoverlay

## Reproduction rate
 Every time

## Expected result

Doesnt pause the game. Pretty sure it cant be fixed.

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

**Comment by anathemamask** [comment]
This resolved it for me: 

**How to not pause game while tabbing.**
1. Navigate to `skyrim.ini` within `\Documents\My Games\Skyrim` or `\My Games\Skyrim Special Edition`
2. Add `bAlwaysActive=1` under `[GENERAL]`
3. Save and the game will no longer pause when alt-tabbed or unselected.

**Comment by Dragonisser** [comment]
That does fix the issue, but we need an solution which comes with the mod directly.

**Comment by Pokang** [comment]
This should not be an issue anymore, since we removed the no pause code, that makes it in line with other menus. Please reopen if it occurs other issues with sync or the mod in general.
