### ISSUE TITLE
Key bindings

### ISSUE THREAD

**Issue by LeonSkull** [SkyrimTogether/issues-game#98]
trying to key bind with mouse but can't.

A clear and concise description of what the bug is, Include any formIDs relevant for us to use ie,

Related formIDs|
---------------|
[Flames - 12FCD](http://en.uesp.net/wiki/Skyrim:Flames)|
[Nazeem - 1A6A4](http://en.uesp.net/wiki/Skyrim:Nazeem)|

## Steps to reproduce

How to reproduce this issue:

1. Start the game.
2. Connect to the server.
3. Crash.

## Reproduction rate

How many times can you reproduce it?

any

Describe your expected result.

cant key bind mouse

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim
    X* The Elder Scrolls V: Skyrim Special Edition

## Evidence (optional)

Show us what happen.

**Comment by Dragonisser** [comment]
Set the keybinds before joining a server. Just a temporary fix.

**Comment by Pokang** [comment]
That was probably related to our no-pause code, which has been deleted since, feel free to reopen if that still happens but it shouldn't.
