### ISSUE TITLE
Pressing PrintScreen make the character speedy

### ISSUE THREAD

**Issue by TheOriginalGeez** [SkyrimTogether/issues-game#99]
## Description

Pressing PrintScreen on the keyboard makes everyone really fast.

## Steps to reproduce

How to reproduce this issue:

1. Start ST.
2. Press PrintScreen (You can either be connected or disconnected to a server it still works.)
3. You go super fast.

## Reproduction rate

Every time.

## Expected result

It doesn't change your speed.

## Your environment

    * The Elder Scrolls V: Skyrim Special Edition

**Comment by Thermalpulse** [comment]
This is not a glitch, it is a feature of Skyrim. Hitting Ctrl+Printscreen removes the refresh rate and unlocks the FPS. When using Right Control to access Skyrim Together's hud, it's considered a toggle and therefore is "stuck" until pressed again.

**Comment by Pokang** [comment]
@Thermalpulse That's a very smart reply, noone in the team had thought of this, I'm not sure we can do anything then, except maybe changing the keybind? 
Thank you for the insight, closing the issue.
